// This file is machine generated by OpenVADL fix-upgrade-gradle-wrapper-jdk25-SNAPSHOT on 25/11/09 08:05:33 UTC
// and is therefore not copyrightable and in the public domain.
// It is recommended to not modify this file, but the sources from which it was generated.

//> using scala "2.13.12"
//> using dep org.chipsalliance::chisel:7.2.0
//> using plugin org.chipsalliance:::chisel-plugin:7.2.0
//> using options -unchecked -deprecation -language:reflectiveCalls -feature -Xcheckinit
//> using options -Xfatal-warnings -Ywarn-dead-code -Ywarn-unused -Ymacro-annotations

import VADL._
import chisel3._
import chisel3.util._
import _root_.circt.stage.ChiselStage

class DECODE extends Module {

  class IO extends Bundle {
    val read_readMEM1_result_in = Flipped(new VADL.RegReadPort(Bits(32.W)))
    val DECODE_en_in = Input(Bool())
    val fwd_X0_en_in = Input(Bool())
    val fwd_X0_val_in = Input(Bits(32.W))
    val readX0_result_in = Flipped(new VADL.RegFileReadPort(Bits(32.W), 5))
    val read_DECODE_full_in = Flipped(new VADL.RegReadPort(Bits(1.W)))
    val fwd_X1_en_in = Input(Bool())
    val fwd_X1_val_in = Input(Bits(32.W))
    val readX1_result_in = Flipped(new VADL.RegFileReadPort(Bits(32.W), 5))
    val read_readMEM1_addr_in = Flipped(new VADL.RegReadPort(Bits(32.W)))
    val read_writePC1_value_in = Flipped(new VADL.RegReadPort(Bits(32.W)))
    val read_n248_out = new VADL.RegReadPort(Bits(3.W))
    val read_rs1_neq_0_out = new VADL.RegReadPort(Bits(1.W))
    val read_readX0_result_out = new VADL.RegReadPort(Bits(32.W))
    val read_rs2_neq_0_out = new VADL.RegReadPort(Bits(1.W))
    val read_readX1_result_out = new VADL.RegReadPort(Bits(32.W))
    val read_writePC1_value_0_out = new VADL.RegReadPort(Bits(32.W))
    val read_readMEM1_addr_0_out = new VADL.RegReadPort(Bits(32.W))
    val read_n204_out = new VADL.RegReadPort(Bits(32.W))
    val read_is_JALRBEQBLTBGEBGEUBNEJALBLTU_out = new VADL.RegReadPort(Bits(1.W))
    val read_bin_writePC0_value_out = new VADL.RegReadPort(Bits(2.W))
    val read_sel_readMEM0_addr_out = new VADL.RegReadPort(Bits(5.W))
    val read_readMEM0_addr_out = new VADL.RegReadPort(Bits(32.W))
    val read_rs2_out = new VADL.RegReadPort(Bits(5.W))
    val read_is_S_out = new VADL.RegReadPort(Bits(1.W))
    val read_sel_writeMEM0_words_out = new VADL.RegReadPort(Bits(2.W))
    val read_invalid_insn_out = new VADL.RegReadPort(Bits(1.W))
    val read_bin_writeX0_value_out = new VADL.RegReadPort(Bits(3.W))
    val read_bin_readMEM0_words_out = new VADL.RegReadPort(Bits(2.W))
    val read_is_L_out = new VADL.RegReadPort(Bits(1.W))
    val read_writeX0_enable_out = new VADL.RegReadPort(Bits(1.W))
    val read_rd_out = new VADL.RegReadPort(Bits(5.W))
    val rs1_out = Output(Bits(5.W))
    val readX1_addr_out = Output(Bits(5.W))
    val readX0_enable_out = Output(Bits(1.W))
    val readX1_enable_out = Output(Bits(1.W))

  }
  val io = IO(new IO)



  val rs1 = Wire(Bits(5.W))
  val readX1_addr = Wire(Bits(5.W))
  val readX0_enable = Wire(Bits(1.W))
  val readX1_enable = Wire(Bits(1.W))
  val rd = RegInit(0.U.asTypeOf(Bits(5.W)))
  val rs2 = RegInit(0.U.asTypeOf(Bits(5.W)))
  val readMEM0_addr = RegInit(0.U.asTypeOf(Bits(32.W)))
  val rs1_neq_0 = RegInit(0.U.asTypeOf(Bits(1.W)))
  val rs2_neq_0 = RegInit(0.U.asTypeOf(Bits(1.W)))
  val n204 = RegInit(0.U.asTypeOf(Bits(32.W)))
  val writeX0_enable = RegInit(0.U.asTypeOf(Bits(1.W)))
  val is_JALRBEQBLTBGEBGEUBNEJALBLTU = RegInit(0.U.asTypeOf(Bits(1.W)))
  val is_S = RegInit(0.U.asTypeOf(Bits(1.W)))
  val is_L = RegInit(0.U.asTypeOf(Bits(1.W)))
  val n248 = RegInit(0.U.asTypeOf(Bits(3.W)))
  val bin_writePC0_value = RegInit(0.U.asTypeOf(Bits(2.W)))
  val bin_readMEM0_words = RegInit(0.U.asTypeOf(Bits(2.W)))
  val sel_writeMEM0_words = RegInit(0.U.asTypeOf(Bits(2.W)))
  val bin_writeX0_value = RegInit(0.U.asTypeOf(Bits(3.W)))
  val sel_readMEM0_addr = RegInit(0.U.asTypeOf(Bits(5.W)))
  val invalid_insn = RegInit(0.U.asTypeOf(Bits(1.W)))
  val readX0_result = RegInit(0.U.asTypeOf(Bits(32.W)))
  val readX1_result = RegInit(0.U.asTypeOf(Bits(32.W)))
  val readMEM1_addr = RegInit(0.U.asTypeOf(Bits(32.W)))
  val writePC1_value = RegInit(0.U.asTypeOf(Bits(32.W)))
  val dec_n_253 = Wire(Bits(3.W))
  val dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB = Wire(Bool())
  val dec_n_238 = Wire(Bool())
  val dec_writeMEM0_enable = Wire(Bool())
  val dec_readMEM0_enable = Wire(Bool())
  val dec_n_248 = Wire(Bits(3.W))
  val dec_sel_writePC0_value = Wire(Bits(2.W))
  val dec_sel_readMEM0_words = Wire(Bits(2.W))
  val dec_bin_writeMEM0_words = Wire(Bits(2.W))
  val dec_sel_writeX0_value = Wire(Bits(3.W))
  val dec_bin_readMEM0_addr = Wire(Bits(5.W))
  val dec_n_255 = Wire(Bool())
  val dec_is_not_AUIPCLUIJALECALLEBREAK = Wire(Bool())
  val dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB = Wire(Bool())
  val writeX0_value = Wire(Bits(32.W))
  val n_162 = Wire(Bool())
  val n_166 = Wire(Bool())
  val rs1_neq_0_and_is_not_AUIPCLUIJ = Wire(Bits(1.W))
  val sig_79 = Wire(Bits(32.W))
  val rs2_neq_0_and_is_SLLSHSLTUBGEX = Wire(Bits(1.W))
  val sig_85 = Wire(Bits(32.W))


  when (io.read_readMEM1_result_in.data.asUInt === BitPat("b0010011????????????????????????")) {
    when (io.read_readMEM1_result_in.data.asUInt === BitPat("b100????????????????????")) {
      // XORI
      dec_n_253 := 0.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := true.B
      dec_n_238 := false.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 5.U
      dec_bin_readMEM0_addr := 15.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := false.B
    }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b001????????????????????")) {
      when (io.read_readMEM1_result_in.data.asUInt === BitPat("b0000000?")) {
        // SLLI
        dec_n_253 := 0.U
        dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := true.B
        dec_n_238 := false.B
        dec_writeMEM0_enable := false.B
        dec_readMEM0_enable := false.B
        dec_n_248 := 0.U
        dec_sel_writePC0_value := 0.U
        dec_sel_readMEM0_words := 0.U
        dec_bin_writeMEM0_words := 0.U
        dec_sel_writeX0_value := 5.U
        dec_bin_readMEM0_addr := 20.U
        dec_n_255 := false.B
        dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
        dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := false.B
      }.otherwise {
        // Invalid
        dec_n_253 := 0.U
        dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := false.B
        dec_n_238 := false.B
        dec_writeMEM0_enable := false.B
        dec_readMEM0_enable := false.B
        dec_n_248 := 0.U
        dec_sel_writePC0_value := 0.U
        dec_sel_readMEM0_words := 0.U
        dec_bin_writeMEM0_words := 0.U
        dec_sel_writeX0_value := 0.U
        dec_bin_readMEM0_addr := 0.U
        dec_n_255 := true.B
        dec_is_not_AUIPCLUIJALECALLEBREAK := false.B
        dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := false.B
      }
    }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b101????????????????????")) {
      when (io.read_readMEM1_result_in.data.asUInt === BitPat("b0000000?")) {
        // SRLI
        dec_n_253 := 0.U
        dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := true.B
        dec_n_238 := false.B
        dec_writeMEM0_enable := false.B
        dec_readMEM0_enable := false.B
        dec_n_248 := 0.U
        dec_sel_writePC0_value := 0.U
        dec_sel_readMEM0_words := 0.U
        dec_bin_writeMEM0_words := 0.U
        dec_sel_writeX0_value := 5.U
        dec_bin_readMEM0_addr := 21.U
        dec_n_255 := false.B
        dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
        dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := false.B
      }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b0100000?")) {
        // SRAI
        dec_n_253 := 0.U
        dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := true.B
        dec_n_238 := false.B
        dec_writeMEM0_enable := false.B
        dec_readMEM0_enable := false.B
        dec_n_248 := 0.U
        dec_sel_writePC0_value := 0.U
        dec_sel_readMEM0_words := 0.U
        dec_bin_writeMEM0_words := 0.U
        dec_sel_writeX0_value := 5.U
        dec_bin_readMEM0_addr := 22.U
        dec_n_255 := false.B
        dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
        dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := false.B
      }.otherwise {
        // Invalid
        dec_n_253 := 0.U
        dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := false.B
        dec_n_238 := false.B
        dec_writeMEM0_enable := false.B
        dec_readMEM0_enable := false.B
        dec_n_248 := 0.U
        dec_sel_writePC0_value := 0.U
        dec_sel_readMEM0_words := 0.U
        dec_bin_writeMEM0_words := 0.U
        dec_sel_writeX0_value := 0.U
        dec_bin_readMEM0_addr := 0.U
        dec_n_255 := true.B
        dec_is_not_AUIPCLUIJALECALLEBREAK := false.B
        dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := false.B
      }
    }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b111????????????????????")) {
      // ANDI
      dec_n_253 := 0.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := true.B
      dec_n_238 := false.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 5.U
      dec_bin_readMEM0_addr := 13.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := false.B
    }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b000????????????????????")) {
      // ADDI
      dec_n_253 := 0.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := true.B
      dec_n_238 := false.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 5.U
      dec_bin_readMEM0_addr := 12.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := false.B
    }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b110????????????????????")) {
      // ORI
      dec_n_253 := 0.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := true.B
      dec_n_238 := false.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 5.U
      dec_bin_readMEM0_addr := 14.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := false.B
    }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b010????????????????????")) {
      // SLTI
      dec_n_253 := 0.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := true.B
      dec_n_238 := false.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 5.U
      dec_bin_readMEM0_addr := 16.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := false.B
    }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b011????????????????????")) {
      // SLTIU
      dec_n_253 := 0.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := true.B
      dec_n_238 := false.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 5.U
      dec_bin_readMEM0_addr := 17.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := false.B
    }.otherwise {
      // Invalid
      dec_n_253 := 0.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := false.B
      dec_n_238 := false.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 0.U
      dec_bin_readMEM0_addr := 0.U
      dec_n_255 := true.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := false.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := false.B
    }
  }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b0110011????????????????????????")) {
    when (io.read_readMEM1_result_in.data.asUInt === BitPat("b001????????????0000000?")) {
      // SLL
      dec_n_253 := 0.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := true.B
      dec_n_238 := false.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 5.U
      dec_bin_readMEM0_addr := 9.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := true.B
    }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b011????????????0000000?")) {
      // SLTU
      dec_n_253 := 0.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := true.B
      dec_n_238 := false.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 5.U
      dec_bin_readMEM0_addr := 8.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := true.B
    }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b100????????????0000000?")) {
      // XOR
      dec_n_253 := 0.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := true.B
      dec_n_238 := false.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 5.U
      dec_bin_readMEM0_addr := 6.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := true.B
    }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b000????????????0100000?")) {
      // SUB
      dec_n_253 := 0.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := true.B
      dec_n_238 := false.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 5.U
      dec_bin_readMEM0_addr := 3.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := true.B
    }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b101????????????0000000?")) {
      // SRL
      dec_n_253 := 0.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := true.B
      dec_n_238 := false.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 5.U
      dec_bin_readMEM0_addr := 10.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := true.B
    }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b110????????????0000000?")) {
      // OR
      dec_n_253 := 0.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := true.B
      dec_n_238 := false.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 5.U
      dec_bin_readMEM0_addr := 5.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := true.B
    }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b000????????????0000000?")) {
      // ADD
      dec_n_253 := 0.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := true.B
      dec_n_238 := false.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 5.U
      dec_bin_readMEM0_addr := 2.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := true.B
    }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b111????????????0000000?")) {
      // AND
      dec_n_253 := 0.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := true.B
      dec_n_238 := false.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 5.U
      dec_bin_readMEM0_addr := 4.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := true.B
    }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b010????????????0000000?")) {
      // SLT
      dec_n_253 := 0.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := true.B
      dec_n_238 := false.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 5.U
      dec_bin_readMEM0_addr := 7.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := true.B
    }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b101????????????0100000?")) {
      // SRA
      dec_n_253 := 0.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := true.B
      dec_n_238 := false.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 5.U
      dec_bin_readMEM0_addr := 11.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := true.B
    }.otherwise {
      // Invalid
      dec_n_253 := 0.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := false.B
      dec_n_238 := false.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 0.U
      dec_bin_readMEM0_addr := 0.U
      dec_n_255 := true.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := false.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := false.B
    }
  }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b1100111????????????????????????")) {
    when (io.read_readMEM1_result_in.data.asUInt === BitPat("b000????????????????????")) {
      // JALR
      dec_n_253 := 0.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := true.B
      dec_n_238 := true.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 7.U
      dec_sel_writePC0_value := 2.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 5.U
      dec_bin_readMEM0_addr := 23.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := false.B
    }.otherwise {
      // Invalid
      dec_n_253 := 0.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := false.B
      dec_n_238 := false.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 0.U
      dec_bin_readMEM0_addr := 0.U
      dec_n_255 := true.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := false.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := false.B
    }
  }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b0000011????????????????????????")) {
    when (io.read_readMEM1_result_in.data.asUInt === BitPat("b100????????????????????")) {
      // LBU
      dec_n_253 := 0.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := true.B
      dec_n_238 := false.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := true.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 1.U
      dec_bin_readMEM0_addr := 1.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := false.B
    }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b001????????????????????")) {
      // LH
      dec_n_253 := 0.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := true.B
      dec_n_238 := false.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := true.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 2.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 2.U
      dec_bin_readMEM0_addr := 1.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := false.B
    }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b000????????????????????")) {
      // LB
      dec_n_253 := 0.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := true.B
      dec_n_238 := false.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := true.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 0.U
      dec_bin_readMEM0_addr := 1.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := false.B
    }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b010????????????????????")) {
      // LW
      dec_n_253 := 0.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := true.B
      dec_n_238 := false.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := true.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 1.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 4.U
      dec_bin_readMEM0_addr := 1.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := false.B
    }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b101????????????????????")) {
      // LHU
      dec_n_253 := 0.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := true.B
      dec_n_238 := false.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := true.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 2.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 3.U
      dec_bin_readMEM0_addr := 1.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := false.B
    }.otherwise {
      // Invalid
      dec_n_253 := 0.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := false.B
      dec_n_238 := false.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 0.U
      dec_bin_readMEM0_addr := 0.U
      dec_n_255 := true.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := false.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := false.B
    }
  }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b1100011????????????????????????")) {
    when (io.read_readMEM1_result_in.data.asUInt === BitPat("b101????????????????????")) {
      // BGE
      dec_n_253 := 4.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := false.B
      dec_n_238 := true.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 2.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 0.U
      dec_bin_readMEM0_addr := 0.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := true.B
    }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b000????????????????????")) {
      // BEQ
      dec_n_253 := 4.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := false.B
      dec_n_238 := true.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 0.U
      dec_bin_readMEM0_addr := 0.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := true.B
    }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b100????????????????????")) {
      // BLT
      dec_n_253 := 4.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := false.B
      dec_n_238 := true.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 4.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 0.U
      dec_bin_readMEM0_addr := 0.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := true.B
    }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b110????????????????????")) {
      // BLTU
      dec_n_253 := 4.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := false.B
      dec_n_238 := true.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 5.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 0.U
      dec_bin_readMEM0_addr := 0.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := true.B
    }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b111????????????????????")) {
      // BGEU
      dec_n_253 := 4.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := false.B
      dec_n_238 := true.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 3.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 0.U
      dec_bin_readMEM0_addr := 0.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := true.B
    }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b001????????????????????")) {
      // BNE
      dec_n_253 := 4.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := false.B
      dec_n_238 := true.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 1.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 0.U
      dec_bin_readMEM0_addr := 0.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := true.B
    }.otherwise {
      // Invalid
      dec_n_253 := 0.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := false.B
      dec_n_238 := false.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 0.U
      dec_bin_readMEM0_addr := 0.U
      dec_n_255 := true.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := false.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := false.B
    }
  }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b0100011????????????????????????")) {
    when (io.read_readMEM1_result_in.data.asUInt === BitPat("b010????????????????????")) {
      // SW
      dec_n_253 := 3.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := false.B
      dec_n_238 := false.B
      dec_writeMEM0_enable := true.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 2.U
      dec_sel_writeX0_value := 0.U
      dec_bin_readMEM0_addr := 0.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := true.B
    }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b001????????????????????")) {
      // SH
      dec_n_253 := 3.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := false.B
      dec_n_238 := false.B
      dec_writeMEM0_enable := true.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 1.U
      dec_sel_writeX0_value := 0.U
      dec_bin_readMEM0_addr := 0.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := true.B
    }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b000????????????????????")) {
      // SB
      dec_n_253 := 3.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := false.B
      dec_n_238 := false.B
      dec_writeMEM0_enable := true.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 0.U
      dec_bin_readMEM0_addr := 0.U
      dec_n_255 := false.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := true.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := true.B
    }.otherwise {
      // Invalid
      dec_n_253 := 0.U
      dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := false.B
      dec_n_238 := false.B
      dec_writeMEM0_enable := false.B
      dec_readMEM0_enable := false.B
      dec_n_248 := 0.U
      dec_sel_writePC0_value := 0.U
      dec_sel_readMEM0_words := 0.U
      dec_bin_writeMEM0_words := 0.U
      dec_sel_writeX0_value := 0.U
      dec_bin_readMEM0_addr := 0.U
      dec_n_255 := true.B
      dec_is_not_AUIPCLUIJALECALLEBREAK := false.B
      dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := false.B
    }
  }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b1101111????????????????????????")) {
    // JAL
    dec_n_253 := 2.U
    dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := true.B
    dec_n_238 := true.B
    dec_writeMEM0_enable := false.B
    dec_readMEM0_enable := false.B
    dec_n_248 := 6.U
    dec_sel_writePC0_value := 1.U
    dec_sel_readMEM0_words := 0.U
    dec_bin_writeMEM0_words := 0.U
    dec_sel_writeX0_value := 5.U
    dec_bin_readMEM0_addr := 23.U
    dec_n_255 := false.B
    dec_is_not_AUIPCLUIJALECALLEBREAK := false.B
    dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := false.B
  }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b0110111????????????????????????")) {
    // LUI
    dec_n_253 := 0.U
    dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := true.B
    dec_n_238 := false.B
    dec_writeMEM0_enable := false.B
    dec_readMEM0_enable := false.B
    dec_n_248 := 0.U
    dec_sel_writePC0_value := 0.U
    dec_sel_readMEM0_words := 0.U
    dec_bin_writeMEM0_words := 0.U
    dec_sel_writeX0_value := 5.U
    dec_bin_readMEM0_addr := 19.U
    dec_n_255 := false.B
    dec_is_not_AUIPCLUIJALECALLEBREAK := false.B
    dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := false.B
  }.elsewhen (io.read_readMEM1_result_in.data.asUInt === BitPat("b0010111????????????????????????")) {
    // AUIPC
    dec_n_253 := 1.U
    dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := true.B
    dec_n_238 := false.B
    dec_writeMEM0_enable := false.B
    dec_readMEM0_enable := false.B
    dec_n_248 := 0.U
    dec_sel_writePC0_value := 0.U
    dec_sel_readMEM0_words := 0.U
    dec_bin_writeMEM0_words := 0.U
    dec_sel_writeX0_value := 5.U
    dec_bin_readMEM0_addr := 18.U
    dec_n_255 := false.B
    dec_is_not_AUIPCLUIJALECALLEBREAK := false.B
    dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := false.B
  }.otherwise {
    // Invalid
    dec_n_253 := 0.U
    dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB := false.B
    dec_n_238 := false.B
    dec_writeMEM0_enable := false.B
    dec_readMEM0_enable := false.B
    dec_n_248 := 0.U
    dec_sel_writePC0_value := 0.U
    dec_sel_readMEM0_words := 0.U
    dec_bin_writeMEM0_words := 0.U
    dec_sel_writeX0_value := 0.U
    dec_bin_readMEM0_addr := 0.U
    dec_n_255 := true.B
    dec_is_not_AUIPCLUIJALECALLEBREAK := false.B
    dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB := false.B
  }

  when ((io.DECODE_en_in).asBool) {
    rd := io.read_readMEM1_result_in.data.asUInt(11, 7)
  }
  when ((io.DECODE_en_in).asBool) {
    rs2 := io.read_readMEM1_result_in.data.asUInt(24, 20)
  }
  writeX0_value := lsl(io.read_readMEM1_result_in.data.asUInt(31, 12).sext(32.W), "hc".U(4.W))
  when ((io.DECODE_en_in).asBool) {
    readMEM0_addr := writeX0_value
  }
  n_162 := neq(io.read_readMEM1_result_in.data.asUInt(19, 15), "h0".U(5.W))
  when ((io.DECODE_en_in).asBool) {
    rs1_neq_0 := n_162
  }
  n_166 := neq(io.read_readMEM1_result_in.data.asUInt(24, 20), "h0".U(5.W))
  when ((io.DECODE_en_in).asBool) {
    rs2_neq_0 := n_166
  }
  when ((io.DECODE_en_in).asBool) {
    n204 := MuxLookup[Bits](dec_n_253, 0.U)(Seq(0.U -> io.read_readMEM1_result_in.data.asUInt(31, 20).sext(32.W), 1.U -> writeX0_value, 2.U -> lsl(Cat(io.read_readMEM1_result_in.data.asUInt(31, 31), io.read_readMEM1_result_in.data.asUInt(19, 12), io.read_readMEM1_result_in.data.asUInt(20, 20), io.read_readMEM1_result_in.data.asUInt(30, 21)).sext(32.W), "h1".U(1.W)), 3.U -> Cat(io.read_readMEM1_result_in.data.asUInt(31, 25), io.read_readMEM1_result_in.data.asUInt(11, 7)).sext(32.W), 4.U -> lsl(Cat(io.read_readMEM1_result_in.data.asUInt(31, 31), io.read_readMEM1_result_in.data.asUInt(7, 7), io.read_readMEM1_result_in.data.asUInt(30, 25), io.read_readMEM1_result_in.data.asUInt(11, 8)).sext(32.W), "h1".U(1.W))))
  }
  when ((io.DECODE_en_in).asBool) {
    writeX0_enable := and(neq(io.read_readMEM1_result_in.data.asUInt(11, 7), "h0".U(5.W)), dec_is_not_SBSHSWBEQBNEBGEBGEUBLTB)
  }
  when ((io.DECODE_en_in).asBool) {
    is_JALRBEQBLTBGEBGEUBNEJALBLTU := dec_n_238
  }
  when ((io.DECODE_en_in).asBool) {
    is_S := dec_writeMEM0_enable
  }
  when ((io.DECODE_en_in).asBool) {
    is_L := dec_readMEM0_enable
  }
  when ((io.DECODE_en_in).asBool) {
    n248 := dec_n_248
  }
  when ((io.DECODE_en_in).asBool) {
    bin_writePC0_value := dec_sel_writePC0_value
  }
  when ((io.DECODE_en_in).asBool) {
    bin_readMEM0_words := dec_sel_readMEM0_words
  }
  when ((io.DECODE_en_in).asBool) {
    sel_writeMEM0_words := dec_bin_writeMEM0_words
  }
  when ((io.DECODE_en_in).asBool) {
    bin_writeX0_value := dec_sel_writeX0_value
  }
  when ((io.DECODE_en_in).asBool) {
    sel_readMEM0_addr := dec_bin_readMEM0_addr
  }
  when ((io.DECODE_en_in).asBool) {
    invalid_insn := dec_n_255
  }
  rs1_neq_0_and_is_not_AUIPCLUIJ := and(n_162, dec_is_not_AUIPCLUIJALECALLEBREAK)
  io.readX0_result_in.enable := and(io.read_DECODE_full_in.data.asUInt, and(rs1_neq_0_and_is_not_AUIPCLUIJ, not(io.fwd_X0_en_in)))
  io.readX0_result_in.address := io.read_readMEM1_result_in.data.asUInt(19, 15)
  sig_79 := Mux((io.fwd_X0_en_in).asBool, io.fwd_X0_val_in, io.readX0_result_in.data.asUInt)
  when ((io.DECODE_en_in).asBool) {
    readX0_result := sig_79
  }
  rs2_neq_0_and_is_SLLSHSLTUBGEX := and(n_166, dec_is_SLLSHSLTUBGEXORSUBSRLBEQSBB)
  io.readX1_result_in.enable := and(io.read_DECODE_full_in.data.asUInt, and(rs2_neq_0_and_is_SLLSHSLTUBGEX, not(io.fwd_X1_en_in)))
  io.readX1_result_in.address := io.read_readMEM1_result_in.data.asUInt(24, 20)
  sig_85 := Mux((io.fwd_X1_en_in).asBool, io.fwd_X1_val_in, io.readX1_result_in.data.asUInt)
  when ((io.DECODE_en_in).asBool) {
    readX1_result := sig_85
  }
  when ((io.DECODE_en_in).asBool) {
    readMEM1_addr := io.read_readMEM1_addr_in.data.asUInt
  }
  when ((io.DECODE_en_in).asBool) {
    writePC1_value := io.read_writePC1_value_in.data.asUInt
  }
  rs1 := io.read_readMEM1_result_in.data.asUInt(19, 15)
  readX1_addr := io.read_readMEM1_result_in.data.asUInt(24, 20)
  readX0_enable := rs1_neq_0_and_is_not_AUIPCLUIJ
  readX1_enable := rs2_neq_0_and_is_SLLSHSLTUBGEX
  when ((rs1_neq_0_and_is_not_AUIPCLUIJ).asBool) {
    printf(cf"%T ${io.read_readMEM1_addr_in.data.asUInt}%x rd X(${io.read_readMEM1_result_in.data.asUInt(19, 15)}%d) = ${sig_79}%x\n")
  }
  when ((rs2_neq_0_and_is_SLLSHSLTUBGEX).asBool) {
    printf(cf"%T ${io.read_readMEM1_addr_in.data.asUInt}%x rd X(${io.read_readMEM1_result_in.data.asUInt(24, 20)}%d) = ${sig_85}%x\n")
  }
  io.read_n248_out := n248
  io.read_rs1_neq_0_out := rs1_neq_0
  io.read_readX0_result_out := readX0_result
  io.read_rs2_neq_0_out := rs2_neq_0
  io.read_readX1_result_out := readX1_result
  io.read_writePC1_value_0_out := writePC1_value
  io.read_readMEM1_addr_0_out := readMEM1_addr
  io.read_n204_out := n204
  io.read_is_JALRBEQBLTBGEBGEUBNEJALBLTU_out := is_JALRBEQBLTBGEBGEUBNEJALBLTU
  io.read_bin_writePC0_value_out := bin_writePC0_value
  io.read_sel_readMEM0_addr_out := sel_readMEM0_addr
  io.read_readMEM0_addr_out := readMEM0_addr
  io.read_rs2_out := rs2
  io.read_is_S_out := is_S
  io.read_sel_writeMEM0_words_out := sel_writeMEM0_words
  io.read_invalid_insn_out := invalid_insn
  io.read_bin_writeX0_value_out := bin_writeX0_value
  io.read_bin_readMEM0_words_out := bin_readMEM0_words
  io.read_is_L_out := is_L
  io.read_writeX0_enable_out := writeX0_enable
  io.read_rd_out := rd
  io.rs1_out := rs1
  io.readX1_addr_out := readX1_addr
  io.readX0_enable_out := readX0_enable
  io.readX1_enable_out := readX1_enable


}

object Main extends App {
  println(
    ChiselStage.emitSystemVerilog(
      gen = new DECODE,
      firtoolOpts = Array(
        "-disable-all-randomization",
        "--lowering-options=disallowLocalVariables",
        "-strip-debug-info")
    )
  )
}