// This file is machine generated by OpenVADL master-SNAPSHOT on 25/10/12 07:56:55 UTC
// and is therefore not copyrightable and in the public domain.
// It is recommended to not modify this file, but the sources from which it was generated.

//> using scala "2.13.12"
//> using dep "org.chipsalliance::chisel:6.6.0"
//> using plugin "org.chipsalliance:::chisel-plugin:6.6.0"
//> using options "-unchecked", "-deprecation", "-language:reflectiveCalls", "-feature", "-Xcheckinit", "-Xfatal-warnings", "-Ywarn-dead-code", "-Ywarn-unused", "-Ymacro-annotations"

import _root_.circt.stage.ChiselStage

import chisel3._
import chisel3.util._
import VADL._

class DECODE extends Module {

  class IO extends Bundle {
    val DECODE_en_in = Input(Bool())
    val read_readMEM1_result_in = Flipped(new VADL.RegReadPort(Bits(32.W)))
    val fwd_X0_en_in = Input(Bool())
    val fwd_X0_val_in = Input(Bits(32.W))
    val readX0_result_in = Flipped(new VADL.RegFileReadPort(Bits(32.W), 5))
    val read_DECODE_full_in = Flipped(new VADL.RegReadPort(Bits(1.W)))
    val fwd_X1_en_in = Input(Bool())
    val fwd_X1_val_in = Input(Bits(32.W))
    val readX1_result_in = Flipped(new VADL.RegFileReadPort(Bits(32.W), 5))
    val read_readMEM1_addr_in = Flipped(new VADL.RegReadPort(Bits(32.W)))
    val read_writePC1_value_in = Flipped(new VADL.RegReadPort(Bits(32.W)))
    val read_bin_is_BEQ_is_BNE_is_BGE_is_BG_out = new VADL.RegReadPort(Bits(3.W))
    val read_rs1_neq_0_out = new VADL.RegReadPort(Bits(1.W))
    val read_readX0_result_out = new VADL.RegReadPort(Bits(32.W))
    val read_rs2_neq_0_out = new VADL.RegReadPort(Bits(1.W))
    val read_readX1_result_out = new VADL.RegReadPort(Bits(32.W))
    val read_writePC1_value_0_out = new VADL.RegReadPort(Bits(32.W))
    val read_readMEM1_addr_0_out = new VADL.RegReadPort(Bits(32.W))
    val read_n204_out = new VADL.RegReadPort(Bits(32.W))
    val read_is_JALRBNEBGEUBGEJALBLTUBEQBLT_out = new VADL.RegReadPort(Bits(1.W))
    val read_sel_writePC0_value_out = new VADL.RegReadPort(Bits(2.W))
    val read_sel_readMEM0_addr_out = new VADL.RegReadPort(Bits(5.W))
    val read_readMEM0_addr_out = new VADL.RegReadPort(Bits(32.W))
    val read_rs2_out = new VADL.RegReadPort(Bits(5.W))
    val read_is_S_out = new VADL.RegReadPort(Bits(1.W))
    val read_sel_writeMEM0_words_out = new VADL.RegReadPort(Bits(2.W))
    val read_not_is_not_none_out = new VADL.RegReadPort(Bits(1.W))
    val read_sel_writeX0_value_out = new VADL.RegReadPort(Bits(3.W))
    val read_sel_readMEM0_words_out = new VADL.RegReadPort(Bits(2.W))
    val read_is_L_out = new VADL.RegReadPort(Bits(1.W))
    val read_writeX0_enable_out = new VADL.RegReadPort(Bits(1.W))
    val read_rd_out = new VADL.RegReadPort(Bits(5.W))
    val rs1_out = Output(Bits(5.W))
    val readX1_addr_out = Output(Bits(5.W))
    val readX0_enable_out = Output(Bits(1.W))
    val readX1_enable_out = Output(Bits(1.W))

  }
  val io = IO(new IO)

  val rs1 = Wire(Bits(5.W))
  val readX1_addr = Wire(Bits(5.W))
  val readX0_enable = Wire(Bits(1.W))
  val readX1_enable = Wire(Bits(1.W))
  val rd = RegInit(0.U.asTypeOf(Bits(5.W)))
  val rs2 = RegInit(0.U.asTypeOf(Bits(5.W)))
  val readMEM0_addr = RegInit(0.U.asTypeOf(Bits(32.W)))
  val rs1_neq_0 = RegInit(0.U.asTypeOf(Bits(1.W)))
  val rs2_neq_0 = RegInit(0.U.asTypeOf(Bits(1.W)))
  val n204 = RegInit(0.U.asTypeOf(Bits(32.W)))
  val writeX0_enable = RegInit(0.U.asTypeOf(Bits(1.W)))
  val is_JALRBNEBGEUBGEJALBLTUBEQBLT = RegInit(0.U.asTypeOf(Bits(1.W)))
  val is_S = RegInit(0.U.asTypeOf(Bits(1.W)))
  val is_L = RegInit(0.U.asTypeOf(Bits(1.W)))
  val bin_is_BEQ_is_BNE_is_BGE_is_BG = RegInit(0.U.asTypeOf(Bits(3.W)))
  val sel_writePC0_value = RegInit(0.U.asTypeOf(Bits(2.W)))
  val sel_readMEM0_words = RegInit(0.U.asTypeOf(Bits(2.W)))
  val sel_writeMEM0_words = RegInit(0.U.asTypeOf(Bits(2.W)))
  val sel_writeX0_value = RegInit(0.U.asTypeOf(Bits(3.W)))
  val sel_readMEM0_addr = RegInit(0.U.asTypeOf(Bits(5.W)))
  val not_is_not_none = RegInit(0.U.asTypeOf(Bits(1.W)))
  val readX0_result = RegInit(0.U.asTypeOf(Bits(32.W)))
  val readX1_result = RegInit(0.U.asTypeOf(Bits(32.W)))
  val readMEM1_addr = RegInit(0.U.asTypeOf(Bits(32.W)))
  val writePC1_value = RegInit(0.U.asTypeOf(Bits(32.W)))
  val writeX0_value = Wire(Bits(32.W))
  val n_162 = Wire(Bool())
  val n_166 = Wire(Bool())

  val is_BNE = Wire(Bool())
  val is_BGEU = Wire(Bool())
  val is_BGE = Wire(Bool())
  val is_BLTU = Wire(Bool())
  val is_BEQ = Wire(Bool())
  val is_BLT = Wire(Bool())

  val sig_152 = Wire(Bits(1.W))

  val is_SH = Wire(Bool())
  val is_SB = Wire(Bool())
  val is_SW = Wire(Bool())

  val sig_147 = Wire(Bits(1.W))

  val is_JAL = Wire(Bool())
  val is_AUIPC = Wire(Bool())
  val is_LH = Wire(Bool())
  val is_JALR = Wire(Bool())
  val is_SLTI = Wire(Bool())
  val is_LB = Wire(Bool())
  val is_ANDI = Wire(Bool())
  val is_SLTIU = Wire(Bool())
  val is_XORI = Wire(Bool())
  val is_LHU = Wire(Bool())
  val is_LW = Wire(Bool())
  val is_LBU = Wire(Bool())
  val is_ADDI = Wire(Bool())
  val is_ORI = Wire(Bool())
  val is_SRA = Wire(Bool())
  val is_SLT = Wire(Bool())
  val is_XOR = Wire(Bool())
  val is_SRLI = Wire(Bool())
  val is_SLL = Wire(Bool())
  val is_SRL = Wire(Bool())
  val is_LUI = Wire(Bool())
  val is_OR = Wire(Bool())
  val is_SLLI = Wire(Bool())
  val is_SUB = Wire(Bool())
  val is_SLTU = Wire(Bool())
  val is_AND = Wire(Bool())
  val is_ADD = Wire(Bool())
  val is_SRAI = Wire(Bool())
  val sig_214 = Wire(Bits(1.W))
  val is_ECALL = Wire(Bool())
  val is_EBREAK = Wire(Bool())

  when ((io.DECODE_en_in).asBool) {
    rd := io.read_readMEM1_result_in.data.asUInt(11, 7)
  }
  when ((io.DECODE_en_in).asBool) {
    rs2 := io.read_readMEM1_result_in.data.asUInt(24, 20)
  }
  writeX0_value := lsl(io.read_readMEM1_result_in.data.asUInt(31, 12).sext(32.W), "hc".U(4.W))
  when ((io.DECODE_en_in).asBool) {
    readMEM0_addr := writeX0_value
  }
  n_162 := neq(io.read_readMEM1_result_in.data.asUInt(19, 15), "h0".U(5.W))
  when ((io.DECODE_en_in).asBool) {
    rs1_neq_0 := n_162
  }
  n_166 := neq(io.read_readMEM1_result_in.data.asUInt(24, 20), "h0".U(5.W))
  when ((io.DECODE_en_in).asBool) {
    rs2_neq_0 := n_166
  }

  is_BNE := BitPat("b?????????????????001?????1100011").matches(io.read_readMEM1_result_in.data.asUInt)
  is_BGEU := BitPat("b?????????????????111?????1100011").matches(io.read_readMEM1_result_in.data.asUInt)
  is_BGE := BitPat("b?????????????????101?????1100011").matches(io.read_readMEM1_result_in.data.asUInt)
  is_BLTU := BitPat("b?????????????????110?????1100011").matches(io.read_readMEM1_result_in.data.asUInt)
  is_BEQ := BitPat("b?????????????????000?????1100011").matches(io.read_readMEM1_result_in.data.asUInt)
  is_BLT := BitPat("b?????????????????100?????1100011").matches(io.read_readMEM1_result_in.data.asUInt)

  sig_152 := or(or(or(or(or(is_BNE, is_BGEU), is_BGE), is_BLTU), is_BEQ), is_BLT)

  is_SH := BitPat("b?????????????????001?????0100011").matches(io.read_readMEM1_result_in.data.asUInt)
  is_SB := BitPat("b?????????????????000?????0100011").matches(io.read_readMEM1_result_in.data.asUInt)
  is_SW := BitPat("b?????????????????010?????0100011").matches(io.read_readMEM1_result_in.data.asUInt)

  sig_147 := or(or(is_SH, is_SB), is_SW)

  is_JAL := BitPat("b?????????????????????????1101111").matches(io.read_readMEM1_result_in.data.asUInt)
  is_AUIPC := BitPat("b?????????????????????????0010111").matches(io.read_readMEM1_result_in.data.asUInt)
  is_LH := BitPat("b?????????????????001?????0000011").matches(io.read_readMEM1_result_in.data.asUInt)
  is_JALR := BitPat("b?????????????????000?????1100111").matches(io.read_readMEM1_result_in.data.asUInt)
  is_SLTI := BitPat("b?????????????????010?????0010011").matches(io.read_readMEM1_result_in.data.asUInt)
  is_LB := BitPat("b?????????????????000?????0000011").matches(io.read_readMEM1_result_in.data.asUInt)
  is_ANDI := BitPat("b?????????????????111?????0010011").matches(io.read_readMEM1_result_in.data.asUInt)
  is_SLTIU := BitPat("b?????????????????011?????0010011").matches(io.read_readMEM1_result_in.data.asUInt)
  is_XORI := BitPat("b?????????????????100?????0010011").matches(io.read_readMEM1_result_in.data.asUInt)
  is_LHU := BitPat("b?????????????????101?????0000011").matches(io.read_readMEM1_result_in.data.asUInt)
  is_LW := BitPat("b?????????????????010?????0000011").matches(io.read_readMEM1_result_in.data.asUInt)
  is_LBU := BitPat("b?????????????????100?????0000011").matches(io.read_readMEM1_result_in.data.asUInt)
  is_ADDI := BitPat("b?????????????????000?????0010011").matches(io.read_readMEM1_result_in.data.asUInt)
  is_ORI := BitPat("b?????????????????110?????0010011").matches(io.read_readMEM1_result_in.data.asUInt)

  when ((io.DECODE_en_in).asBool) {
    // TODO: extract
    val a0 := OHToUInt(Cat(sig_152, sig_147, is_JAL, is_AUIPC, or(or(or(or(or(or(or(or(or(or(or(is_LH, is_JALR), is_SLTI), is_LB), is_ANDI), is_SLTIU), is_XORI), is_LHU), is_LW), is_LBU), is_ADDI), is_ORI)))
    n204 := MuxLookup[Bits](a0, 0.U)(Seq(0.U -> io.read_readMEM1_result_in.data.asUInt(31, 20).sext(32.W), 1.U -> writeX0_value, 2.U -> lsl(Cat(io.read_readMEM1_result_in.data.asUInt(31, 31), io.read_readMEM1_result_in.data.asUInt(19, 12), io.read_readMEM1_result_in.data.asUInt(20, 20), io.read_readMEM1_result_in.data.asUInt(30, 21)).sext(32.W), "h1".U(1.W)), 3.U -> Cat(io.read_readMEM1_result_in.data.asUInt(31, 25), io.read_readMEM1_result_in.data.asUInt(11, 7)).sext(32.W), 4.U -> lsl(Cat(io.read_readMEM1_result_in.data.asUInt(31, 31), io.read_readMEM1_result_in.data.asUInt(7, 7), io.read_readMEM1_result_in.data.asUInt(30, 25), io.read_readMEM1_result_in.data.asUInt(11, 8)).sext(32.W), "h1".U(1.W))))
  }

  is_SRA := BitPat("b0100000??????????101?????0110011").matches(io.read_readMEM1_result_in.data.asUInt)
  is_SLT := BitPat("b0000000??????????010?????0110011").matches(io.read_readMEM1_result_in.data.asUInt)
  is_XOR := BitPat("b0000000??????????100?????0110011").matches(io.read_readMEM1_result_in.data.asUInt)
  is_SRLI := BitPat("b0000000??????????101?????0010011").matches(io.read_readMEM1_result_in.data.asUInt)
  is_SLL := BitPat("b0000000??????????001?????0110011").matches(io.read_readMEM1_result_in.data.asUInt)
  is_SRL := BitPat("b0000000??????????101?????0110011").matches(io.read_readMEM1_result_in.data.asUInt)
  is_LUI := BitPat("b?????????????????????????0110111").matches(io.read_readMEM1_result_in.data.asUInt)
  is_OR := BitPat("b0000000??????????110?????0110011").matches(io.read_readMEM1_result_in.data.asUInt)
  is_SLLI := BitPat("b0000000??????????001?????0010011").matches(io.read_readMEM1_result_in.data.asUInt)
  is_SUB := BitPat("b0100000??????????000?????0110011").matches(io.read_readMEM1_result_in.data.asUInt)
  is_SLTU := BitPat("b0000000??????????011?????0110011").matches(io.read_readMEM1_result_in.data.asUInt)
  is_AND := BitPat("b0000000??????????111?????0110011").matches(io.read_readMEM1_result_in.data.asUInt)
  is_ADD := BitPat("b0000000??????????000?????0110011").matches(io.read_readMEM1_result_in.data.asUInt)
  is_SRAI := BitPat("b0100000??????????101?????0010011").matches(io.read_readMEM1_result_in.data.asUInt)

  when ((io.DECODE_en_in).asBool) {
    // TODO: extract
    val a1 := or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(is_LB, is_JAL), is_SRA), is_LHU), is_LBU), is_ORI), is_SLT), is_XOR), is_SLTI), is_SRLI), is_LW), is_SLL), is_SRL), is_JALR), is_LUI), is_ANDI), is_XORI), is_OR), is_LH), is_SLLI), is_SUB), is_SLTIU), is_SLTU), is_AND), is_ADD), is_AUIPC), is_ADDI), is_SRAI)
    writeX0_enable := and(neq(io.read_readMEM1_result_in.data.asUInt(11, 7), "h0".U(5.W)), a1)
  }
  when ((io.DECODE_en_in).asBool) {
    // TODO: Extract
    val a2 := or(or(or(or(or(or(or(is_JALR, is_BNE), is_BGEU), is_BGE), is_JAL), is_BLTU), is_BEQ), is_BLT)
    is_JALRBNEBGEUBGEJALBLTUBEQBLT := a2
  }
  when ((io.DECODE_en_in).asBool) {
    is_S := sig_147
  }

  // TODO: extract
  sig_214 := or(or(or(or(is_LH, is_LB), is_LHU), is_LW), is_LBU)
  when ((io.DECODE_en_in).asBool) {
    is_L := sig_214
  }
  when ((io.DECODE_en_in).asBool) {
    // TODO: Extract
    val a3 := OHToUInt(Cat(is_JALR, is_JAL, is_BLTU, is_BLT, is_BGEU, is_BGE, is_BNE, is_BEQ))
    bin_is_BEQ_is_BNE_is_BGE_is_BG := a3
  }
  when ((io.DECODE_en_in).asBool) {
    // TODO: Extract
    val a4 := OHToUInt(Cat(is_JALR, is_JAL, sig_152))
    sel_writePC0_value := a4
  }
  when ((io.DECODE_en_in).asBool) {
    // TODO: Extract
    val a5 := OHToUInt(Cat(or(is_LH, is_LHU), is_LW, or(is_LB, is_LBU)))
    sel_readMEM0_words := a5
  }
  when ((io.DECODE_en_in).asBool) {
    // TODO: Extract
    val a6 := OHToUInt(Cat(is_SW, is_SH, is_SB))
    sel_writeMEM0_words := a6
  }
  when ((io.DECODE_en_in).asBool) {
    // TODO: Extract
    val a7 := OHToUInt(Cat(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(is_SRL, is_JALR), is_LUI), is_JAL), is_ANDI), is_SRA), is_XORI), is_OR), is_ORI), is_SLT), is_SLLI), is_XOR), is_SLTI), is_SUB), is_SLTIU), is_SLTU), is_SRLI), is_AND), is_ADD), is_AUIPC), is_ADDI), is_SLL), is_SRAI), is_LW, is_LHU, is_LH, is_LBU, is_LB))
    sel_writeX0_value := a7
  }
  when ((io.DECODE_en_in).asBool) {
    // TDOO: Extract
    val a8 := OHToUInt(Cat(or(is_JALR, is_JAL), is_SRAI, is_SRLI, is_SLLI, is_LUI, is_AUIPC, is_SLTIU, is_SLTI, is_XORI, is_ORI, is_ANDI, is_ADDI, is_SRA, is_SRL, is_SLL, is_SLTU, is_SLT, is_XOR, is_OR, is_AND, is_SUB, is_ADD, sig_214, sig_147))
    sel_readMEM0_addr := a8
  }

  is_ECALL := BitPat("b00000000000000000000000001110011").matches(io.read_readMEM1_result_in.data.asUInt)
  is_EBREAK := BitPat("b00000000000100000000000001110011").matches(io.read_readMEM1_result_in.data.asUInt)

  when ((io.DECODE_en_in).asBool) {
    // TODO: Extract to fallback
    val a9 := not(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(is_ADD, is_SUB), is_AND), is_OR), is_XOR), is_SLT), is_SLTU), is_SLL), is_SRL), is_SRA), is_ADDI), is_ANDI), is_ORI), is_XORI), is_SLTI), is_SLTIU), is_AUIPC), is_LUI), is_LB), is_LBU), is_LH), is_LHU), is_LW), is_SB), is_SH), is_SW), is_BEQ), is_BNE), is_BGE), is_BGEU), is_BLT), is_BLTU), is_JAL), is_JALR), is_SLLI), is_SRLI), is_SRAI), is_ECALL), is_EBREAK))
    not_is_not_none := a9
  }

  // TODO: Extract
  val a10 := or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(is_LB, is_SRA), is_LHU), is_LBU), is_ORI), is_BLTU), is_SLT), is_XOR), is_BNE), is_SLTI), is_SRLI), is_LW), is_BEQ), is_SB), is_SLL), is_JALR), is_SRL), is_BGEU), is_BGE), is_ANDI), is_XORI), is_OR), is_SH), is_BLT), is_LH), is_SLLI), is_SUB), is_SLTIU), is_SLTU), is_AND), is_ADD), is_ADDI), is_SW), is_SRAI)
  rs1_neq_0_and_is_not_AUIPCLUIJ := and(n_162, a10)
  io.readX0_result_in.enable := and(io.read_DECODE_full_in.data.asUInt, and(rs1_neq_0_and_is_not_AUIPCLUIJ, not(io.fwd_X0_en_in)))
  io.readX0_result_in.address := io.read_readMEM1_result_in.data.asUInt(19, 15)
  sig_122 := Mux((io.fwd_X0_en_in).asBool, io.fwd_X0_val_in, io.readX0_result_in.data.asUInt)

  when ((io.DECODE_en_in).asBool) {
    readX0_result := sig_122
  }

  // TODO: Extract
  val a11 := or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(or(is_SRL, is_BGEU), is_BGE), is_SRA), is_OR), is_SH), is_BLTU), is_BLT), is_SLT), is_XOR), is_BNE), is_SUB), is_SLTU), is_AND), is_ADD), is_SLL), is_SB), is_BEQ), is_SW)
  rs2_neq_0_and_is_SRLBGEUBGESRA := and(n_166, a11)
  io.readX1_result_in.enable := and(io.read_DECODE_full_in.data.asUInt, and(rs2_neq_0_and_is_SRLBGEUBGESRA, not(io.fwd_X1_en_in)))
  io.readX1_result_in.address := io.read_readMEM1_result_in.data.asUInt(24, 20)
  sig_128 := Mux((io.fwd_X1_en_in).asBool, io.fwd_X1_val_in, io.readX1_result_in.data.asUInt)
  when ((io.DECODE_en_in).asBool) {
    readX1_result := sig_128
  }
  when ((io.DECODE_en_in).asBool) {
    readMEM1_addr := io.read_readMEM1_addr_in.data.asUInt
  }
  when ((io.DECODE_en_in).asBool) {
    writePC1_value := io.read_writePC1_value_in.data.asUInt
  }

  rs1 := io.read_readMEM1_result_in.data.asUInt(19, 15)
  readX1_addr := io.read_readMEM1_result_in.data.asUInt(24, 20)
  readX0_enable := rs1_neq_0_and_is_not_AUIPCLUIJ
  readX1_enable := rs2_neq_0_and_is_SRLBGEUBGESRA
  when ((rs1_neq_0_and_is_not_AUIPCLUIJ).asBool) {
    //printf(cf"%T ${io.read_readMEM1_addr_in.data.asUInt}%x rd X(${io.read_readMEM1_result_in.data.asUInt(19, 15)}%d) = ${sig_122}%x\n")
  }
  when ((rs2_neq_0_and_is_SRLBGEUBGESRA).asBool) {
    //printf(cf"%T ${io.read_readMEM1_addr_in.data.asUInt}%x rd X(${io.read_readMEM1_result_in.data.asUInt(24, 20)}%d) = ${sig_128}%x\n")
  }

  io.read_bin_is_BEQ_is_BNE_is_BGE_is_BG_out := bin_is_BEQ_is_BNE_is_BGE_is_BG
  io.read_rs1_neq_0_out := rs1_neq_0
  io.read_readX0_result_out := readX0_result
  io.read_rs2_neq_0_out := rs2_neq_0
  io.read_readX1_result_out := readX1_result
  io.read_writePC1_value_0_out := writePC1_value
  io.read_readMEM1_addr_0_out := readMEM1_addr
  io.read_n204_out := n204
  io.read_is_JALRBNEBGEUBGEJALBLTUBEQBLT_out := is_JALRBNEBGEUBGEJALBLTUBEQBLT
  io.read_sel_writePC0_value_out := sel_writePC0_value
  io.read_sel_readMEM0_addr_out := sel_readMEM0_addr
  io.read_readMEM0_addr_out := readMEM0_addr
  io.read_rs2_out := rs2
  io.read_is_S_out := is_S
  io.read_sel_writeMEM0_words_out := sel_writeMEM0_words
  io.read_not_is_not_none_out := not_is_not_none
  io.read_sel_writeX0_value_out := sel_writeX0_value
  io.read_sel_readMEM0_words_out := sel_readMEM0_words
  io.read_is_L_out := is_L
  io.read_writeX0_enable_out := writeX0_enable
  io.read_rd_out := rd
  io.rs1_out := rs1
  io.readX1_addr_out := readX1_addr
  io.readX0_enable_out := readX0_enable
  io.readX1_enable_out := readX1_enable


}

object Main extends App {
  println(
    ChiselStage.emitSystemVerilog(
      gen = new DECODE,
      firtoolOpts = Array("-disable-all-randomization", "-strip-debug-info")
    )
  )
}