// Generated by CIRCT firtool-1.133.0
module InstructionDecoder(
  input         clock,
                reset,
                io_DECODE_en_in,
  input  [31:0] io_read_readMEM1_result_in_data,
  input         io_fwd_X0_en_in,
  input  [31:0] io_fwd_X0_val_in,
                io_readX0_result_in_data,
  output        io_readX0_result_in_enable,
  output [4:0]  io_readX0_result_in_address,
  input         io_read_DECODE_full_in_data,
                io_fwd_X1_en_in,
  input  [31:0] io_fwd_X1_val_in,
                io_readX1_result_in_data,
  output        io_readX1_result_in_enable,
  output [4:0]  io_readX1_result_in_address,
  input  [31:0] io_read_readMEM1_addr_in_data,
                io_read_writePC1_value_in_data,
  output [2:0]  io_read_bin_is_BEQ_is_BNE_is_BGE_is_BG_out_data,
  output        io_read_rs1_neq_0_out_data,
  output [31:0] io_read_readX0_result_out_data,
  output        io_read_rs2_neq_0_out_data,
  output [31:0] io_read_readX1_result_out_data,
                io_read_writePC1_value_0_out_data,
                io_read_readMEM1_addr_0_out_data,
                io_read_n204_out_data,
  output        io_read_is_JALRBNEBGEUBGEJALBLTUBEQBLT_out_data,
  output [1:0]  io_read_sel_writePC0_value_out_data,
  output [4:0]  io_read_sel_readMEM0_addr_out_data,
  output [31:0] io_read_readMEM0_addr_out_data,
  output [4:0]  io_read_rs2_out_data,
  output        io_read_is_S_out_data,
  output [1:0]  io_read_sel_writeMEM0_words_out_data,
  output        io_read_not_is_not_none_out_data,
  output [2:0]  io_read_sel_writeX0_value_out_data,
  output [1:0]  io_read_sel_readMEM0_words_out_data,
  output        io_read_is_L_out_data,
                io_read_writeX0_enable_out_data,
  output [4:0]  io_read_rd_out_data,
                io_rs1_out,
                io_readX1_addr_out,
  output        io_readX0_enable_out,
                io_readX1_enable_out
);

  reg  [4:0]       rd;
  reg  [4:0]       rs2;
  reg  [31:0]      readMEM0_addr;
  reg              rs1_neq_0;
  reg              rs2_neq_0;
  reg  [31:0]      n204;
  reg              writeX0_enable;
  reg              is_JALRBNEBGEUBGEJALBLTUBEQBLT;
  reg              is_S;
  reg              is_L;
  reg  [2:0]       bin_is_BEQ_is_BNE_is_BGE_is_BG;
  reg  [1:0]       sel_writePC0_value;
  reg  [1:0]       sel_readMEM0_words;
  reg  [1:0]       sel_writeMEM0_words;
  reg  [2:0]       sel_writeX0_value;
  reg  [4:0]       sel_readMEM0_addr;
  reg              not_is_not_none;
  reg  [31:0]      readX0_result;
  reg  [31:0]      readX1_result;
  reg  [31:0]      readMEM1_addr;
  reg  [31:0]      writePC1_value;
  wire             _GEN = io_read_readMEM1_result_in_data[30:24] == 7'h33;
  wire [9:0]       _GEN_0 =
    {io_read_readMEM1_result_in_data[22:20], io_read_readMEM1_result_in_data[7:1]};
  wire             _GEN_1 = _GEN_0 == 10'h0;
  wire             _GEN_2 = _GEN_0 == 10'h20;
  wire             _GEN_3 = _GEN_0 == 10'h380;
  wire             _GEN_4 = _GEN_0 == 10'h300;
  wire             _GEN_5 = _GEN_0 == 10'h200;
  wire             _GEN_6 = _GEN_0 == 10'h100;
  wire             _GEN_7 = _GEN_0 == 10'h180;
  wire             _GEN_8 = _GEN_0 == 10'h80;
  wire             _GEN_9 = _GEN_0 == 10'h280;
  wire             _GEN_10 = _GEN_0 == 10'h2A0;
  wire             _GEN_11 =
    _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_7 | _GEN_8 | _GEN_9;
  wire             _GEN_12 = _GEN_11 | _GEN_10;
  wire             _GEN_13 = io_read_readMEM1_result_in_data[30:24] == 7'h13;
  wire             _GEN_14 = io_read_readMEM1_result_in_data[22:20] == 3'h6;
  wire             _GEN_15 = io_read_readMEM1_result_in_data[22:20] == 3'h4;
  wire             _GEN_16 = io_read_readMEM1_result_in_data[22:20] == 3'h2;
  wire             _GEN_17 = io_read_readMEM1_result_in_data[22:20] == 3'h1;
  wire             _GEN_18 = io_read_readMEM1_result_in_data[22:20] == 3'h5;
  wire             _GEN_19 = io_read_readMEM1_result_in_data[7:1] == 7'h20;
  wire             _GEN_20 =
    ~(|(io_read_readMEM1_result_in_data[22:20]))
    | (&(io_read_readMEM1_result_in_data[22:20])) | _GEN_14 | _GEN_15 | _GEN_16
    | io_read_readMEM1_result_in_data[22:20] == 3'h3;
  wire             _GEN_21 =
    _GEN_20
    | (_GEN_17
         ? ~(|(io_read_readMEM1_result_in_data[7:1]))
         : _GEN_18 & (~(|(io_read_readMEM1_result_in_data[7:1])) | _GEN_19));
  wire             _GEN_22 = io_read_readMEM1_result_in_data[30:24] == 7'h17;
  wire             _GEN_23 = io_read_readMEM1_result_in_data[30:24] == 7'h37;
  wire             _GEN_24 = io_read_readMEM1_result_in_data[30:24] == 7'h3;
  wire             _GEN_25 = _GEN_17 | _GEN_18;
  wire             _GEN_26 =
    ~(|(io_read_readMEM1_result_in_data[22:20])) | _GEN_15 | _GEN_25;
  wire             _GEN_27 = _GEN_26 | _GEN_16;
  wire             _GEN_28 = io_read_readMEM1_result_in_data[30:24] == 7'h23;
  wire             _GEN_29 = ~(|(io_read_readMEM1_result_in_data[22:20])) | _GEN_17;
  wire             _GEN_30 = _GEN_29 | _GEN_16;
  wire             _GEN_31 = io_read_readMEM1_result_in_data[30:24] == 7'h63;
  wire             _GEN_32 =
    ~(|(io_read_readMEM1_result_in_data[22:20])) | _GEN_17 | _GEN_18
    | (&(io_read_readMEM1_result_in_data[22:20])) | _GEN_15;
  wire             _GEN_33 = _GEN_32 | _GEN_14;
  wire             _GEN_34 = io_read_readMEM1_result_in_data[30:24] == 7'h6F;
  wire             _GEN_35 = io_read_readMEM1_result_in_data[30:24] == 7'h67;
  wire             _GEN_36 = _GEN_23 | _GEN_24;
  wire             _GEN_37 = _GEN_13 | _GEN_22 | _GEN_36;
  wire             _GEN_38 = _GEN_22 | _GEN_23;
  wire             _GEN_39 = _GEN_35 & ~(|(io_read_readMEM1_result_in_data[22:20]));
  wire             readX0_enable =
    (|(io_read_readMEM1_result_in_data[19:15]))
    & (_GEN
         ? _GEN_12
         : _GEN_13
             ? _GEN_21
             : ~_GEN_38
               & (_GEN_24
                    ? _GEN_27
                    : _GEN_28 ? _GEN_30 : _GEN_31 ? _GEN_33 : ~_GEN_34 & _GEN_39));
  wire             readX1_enable =
    (|(io_read_readMEM1_result_in_data[24:20]))
    & (_GEN ? _GEN_12 : ~_GEN_37 & (_GEN_28 ? _GEN_30 : _GEN_31 & _GEN_33));
  wire [23:0]      _GEN_40 = {3'h3, 3'h5, 3'h2, 3'h4, 3'h0, 3'h0, 3'h1, 3'h0};
  wire             _GEN_41 = io_read_readMEM1_result_in_data[22:20] != 3'h2;
  wire [24:0]      _GEN_42 =
    {io_read_readMEM1_result_in_data[31], io_read_readMEM1_result_in_data[23:0]};
  wire             _GEN_43 = _GEN_34 | _GEN_39;
  wire             _GEN_44 = _GEN_28 | _GEN_31;
  wire             _GEN_45 = _GEN | _GEN_13;
  wire             _GEN_46 = _GEN_35 & ~(|(io_read_readMEM1_result_in_data[22:20]));
  wire             _GEN_47 = _GEN_45 | _GEN_22 | _GEN_23;
  wire             _GEN_48 = _GEN_47 | _GEN_24;
  wire             _GEN_49 = _GEN_48 | _GEN_28;
  wire             _GEN_50 = _GEN_44 | ~(_GEN_34 | _GEN_46);
  wire [31:0]      writeX0_value = {io_read_readMEM1_result_in_data[31:12], 12'h0};
  wire [19:0]      _GEN_51 = {20{io_read_readMEM1_result_in_data[31]}};
  wire [7:0][31:0] _GEN_52 =
    {{32'h0},
     {32'h0},
     {32'h0},
     {{{20{io_read_readMEM1_result_in_data[31]}},
       io_read_readMEM1_result_in_data[7],
       io_read_readMEM1_result_in_data[30:25],
       io_read_readMEM1_result_in_data[11:8],
       1'h0}},
     {{_GEN_51,
       io_read_readMEM1_result_in_data[31:25],
       io_read_readMEM1_result_in_data[11:7]}},
     {{{12{io_read_readMEM1_result_in_data[31]}},
       io_read_readMEM1_result_in_data[19:12],
       io_read_readMEM1_result_in_data[20],
       io_read_readMEM1_result_in_data[30:21],
       1'h0}},
     {writeX0_value},
     {{_GEN_51, io_read_readMEM1_result_in_data[31:20]}}};
  wire [7:0][4:0]  _GEN_53 =
    {{5'hD},
     {5'hE},
     {(|(io_read_readMEM1_result_in_data[7:1])) ? (_GEN_19 ? 5'h16 : 5'h0) : 5'h15},
     {5'hF},
     {5'h11},
     {5'h10},
     {(|(io_read_readMEM1_result_in_data[7:1])) ? 5'h0 : 5'h14},
     {5'h0}};
  always @(posedge clock) begin
    if (reset) begin
      rd <= 5'h0;
      rs2 <= 5'h0;
      readMEM0_addr <= 32'h0;
      rs1_neq_0 <= 1'h0;
      rs2_neq_0 <= 1'h0;
      n204 <= 32'h0;
      writeX0_enable <= 1'h0;
      is_JALRBNEBGEUBGEJALBLTUBEQBLT <= 1'h0;
      is_S <= 1'h0;
      is_L <= 1'h0;
      bin_is_BEQ_is_BNE_is_BGE_is_BG <= 3'h0;
      sel_writePC0_value <= 2'h0;
      sel_readMEM0_words <= 2'h0;
      sel_writeMEM0_words <= 2'h0;
      sel_writeX0_value <= 3'h0;
      sel_readMEM0_addr <= 5'h0;
      not_is_not_none <= 1'h0;
      readX0_result <= 32'h0;
      readX1_result <= 32'h0;
      readMEM1_addr <= 32'h0;
      writePC1_value <= 32'h0;
    end
    else if (io_DECODE_en_in) begin
      rd <= io_read_readMEM1_result_in_data[11:7];
      rs2 <= io_read_readMEM1_result_in_data[24:20];
      readMEM0_addr <= writeX0_value;
      rs1_neq_0 <= |(io_read_readMEM1_result_in_data[19:15]);
      rs2_neq_0 <= |(io_read_readMEM1_result_in_data[24:20]);
      n204 <=
        _GEN_52[_GEN_45
                  ? 3'h0
                  : _GEN_22
                      ? 3'h1
                      : _GEN_36
                          ? 3'h0
                          : _GEN_28
                              ? (_GEN_29 | _GEN_16 ? 3'h3 : 3'h0)
                              : _GEN_31
                                  ? {~(|(io_read_readMEM1_result_in_data[22:20]))
                                       | _GEN_17 | _GEN_18
                                       | (&(io_read_readMEM1_result_in_data[22:20]))
                                       | _GEN_15 | _GEN_14,
                                     2'h0}
                                  : {1'h0, _GEN_34, 1'h0}];
      writeX0_enable <=
        (|(io_read_readMEM1_result_in_data[11:7]))
        & (_GEN
             ? _GEN_12
             : _GEN_13 ? _GEN_21 : _GEN_38 | (_GEN_24 ? _GEN_27 : ~_GEN_44 & _GEN_43));
      is_JALRBNEBGEUBGEJALBLTUBEQBLT <=
        ~(_GEN | _GEN_13 | _GEN_22 | _GEN_23 | _GEN_24 | _GEN_28)
        & (_GEN_31 ? _GEN_33 : _GEN_43);
      is_S <= ~(_GEN | _GEN_37) & _GEN_28 & _GEN_30;
      is_L <= ~(_GEN | _GEN_13 | _GEN_38) & _GEN_24 & _GEN_27;
      bin_is_BEQ_is_BNE_is_BGE_is_BG <=
        _GEN_49
          ? 3'h0
          : _GEN_31
              ? ((|(io_read_readMEM1_result_in_data[22:20]))
                   ? _GEN_40[io_read_readMEM1_result_in_data[22:20]]
                   : 3'h0)
              : _GEN_34 ? 3'h6 : {3{_GEN_46}};
      sel_writePC0_value <= _GEN_49 | _GEN_31 ? 2'h0 : _GEN_34 ? 2'h1 : {_GEN_46, 1'h0};
      sel_readMEM0_words <=
        _GEN_47 | ~_GEN_24 | ~(|(io_read_readMEM1_result_in_data[22:20])) | _GEN_15
          ? 2'h0
          : _GEN_25 ? 2'h2 : {1'h0, _GEN_16};
      sel_writeMEM0_words <=
        _GEN_48 | ~(_GEN_28 & (|(io_read_readMEM1_result_in_data[22:20])))
          ? 2'h0
          : _GEN_17 ? 2'h1 : {_GEN_16, 1'h0};
      sel_writeX0_value <=
        _GEN
          ? (_GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_7 | _GEN_8
             | _GEN_9 | _GEN_10
               ? 3'h5
               : 3'h0)
          : _GEN_13
              ? (_GEN_20
                   ? 3'h5
                   : _GEN_17
                       ? ((|(io_read_readMEM1_result_in_data[7:1])) ? 3'h0 : 3'h5)
                       : _GEN_18 & (~(|(io_read_readMEM1_result_in_data[7:1])) | _GEN_19)
                           ? 3'h5
                           : 3'h0)
              : _GEN_38
                  ? 3'h5
                  : _GEN_24
                      ? ((|(io_read_readMEM1_result_in_data[22:20]))
                           ? (_GEN_15
                                ? 3'h1
                                : _GEN_17 ? 3'h2 : _GEN_18 ? 3'h3 : {_GEN_16, 2'h0})
                           : 3'h0)
                      : _GEN_50 ? 3'h0 : 3'h5;
      sel_readMEM0_addr <=
        _GEN
          ? (_GEN_1
               ? 5'h2
               : _GEN_2
                   ? 5'h3
                   : _GEN_3
                       ? 5'h4
                       : _GEN_4
                           ? 5'h5
                           : _GEN_5
                               ? 5'h6
                               : _GEN_6
                                   ? 5'h7
                                   : _GEN_7
                                       ? 5'h8
                                       : _GEN_8
                                           ? 5'h9
                                           : _GEN_9 ? 5'hA : _GEN_10 ? 5'hB : 5'h0)
          : _GEN_13
              ? ((|(io_read_readMEM1_result_in_data[22:20]))
                   ? _GEN_53[io_read_readMEM1_result_in_data[22:20]]
                   : 5'hC)
              : _GEN_22
                  ? 5'h12
                  : _GEN_23
                      ? 5'h13
                      : _GEN_24
                          ? {4'h0,
                             ~(|(io_read_readMEM1_result_in_data[22:20])) | _GEN_15
                               | _GEN_17 | _GEN_18 | _GEN_16}
                          : _GEN_50 ? 5'h0 : 5'h17;
      not_is_not_none <=
        _GEN
          ? ~_GEN_11 & _GEN_0 != 10'h2A0
          : _GEN_13
              ? ~_GEN_20
                & (_GEN_17
                     ? (|(io_read_readMEM1_result_in_data[7:1]))
                     : ~_GEN_18 | (|(io_read_readMEM1_result_in_data[7:1]))
                       & io_read_readMEM1_result_in_data[7:1] != 7'h20)
              : ~_GEN_38
                & (_GEN_24
                     ? ~_GEN_26 & _GEN_41
                     : _GEN_28
                         ? ~_GEN_29 & _GEN_41
                         : _GEN_31
                             ? ~_GEN_32 & io_read_readMEM1_result_in_data[22:20] != 3'h6
                             : ~_GEN_34
                               & (_GEN_35
                                    ? (|(io_read_readMEM1_result_in_data[22:20]))
                                    : io_read_readMEM1_result_in_data[30:24] != 7'h73
                                      | (|_GEN_42) & _GEN_42 != 25'h1000));
      readX0_result <= io_fwd_X0_en_in ? io_fwd_X0_val_in : io_readX0_result_in_data;
      readX1_result <= io_fwd_X1_en_in ? io_fwd_X1_val_in : io_readX1_result_in_data;
      readMEM1_addr <= io_read_readMEM1_addr_in_data;
      writePC1_value <= io_read_writePC1_value_in_data;
    end
  end // always @(posedge)
  assign io_readX0_result_in_enable =
    io_read_DECODE_full_in_data & readX0_enable & ~io_fwd_X0_en_in;
  assign io_readX0_result_in_address = io_read_readMEM1_result_in_data[19:15];
  assign io_readX1_result_in_enable =
    io_read_DECODE_full_in_data & readX1_enable & ~io_fwd_X1_en_in;
  assign io_readX1_result_in_address = io_read_readMEM1_result_in_data[24:20];
  assign io_read_bin_is_BEQ_is_BNE_is_BGE_is_BG_out_data = bin_is_BEQ_is_BNE_is_BGE_is_BG;
  assign io_read_rs1_neq_0_out_data = rs1_neq_0;
  assign io_read_readX0_result_out_data = readX0_result;
  assign io_read_rs2_neq_0_out_data = rs2_neq_0;
  assign io_read_readX1_result_out_data = readX1_result;
  assign io_read_writePC1_value_0_out_data = writePC1_value;
  assign io_read_readMEM1_addr_0_out_data = readMEM1_addr;
  assign io_read_n204_out_data = n204;
  assign io_read_is_JALRBNEBGEUBGEJALBLTUBEQBLT_out_data = is_JALRBNEBGEUBGEJALBLTUBEQBLT;
  assign io_read_sel_writePC0_value_out_data = sel_writePC0_value;
  assign io_read_sel_readMEM0_addr_out_data = sel_readMEM0_addr;
  assign io_read_readMEM0_addr_out_data = readMEM0_addr;
  assign io_read_rs2_out_data = rs2;
  assign io_read_is_S_out_data = is_S;
  assign io_read_sel_writeMEM0_words_out_data = sel_writeMEM0_words;
  assign io_read_not_is_not_none_out_data = not_is_not_none;
  assign io_read_sel_writeX0_value_out_data = sel_writeX0_value;
  assign io_read_sel_readMEM0_words_out_data = sel_readMEM0_words;
  assign io_read_is_L_out_data = is_L;
  assign io_read_writeX0_enable_out_data = writeX0_enable;
  assign io_read_rd_out_data = rd;
  assign io_rs1_out = io_read_readMEM1_result_in_data[19:15];
  assign io_readX1_addr_out = io_read_readMEM1_result_in_data[24:20];
  assign io_readX0_enable_out = readX0_enable;
  assign io_readX1_enable_out = readX1_enable;
endmodule
