// Generated by CIRCT firtool-1.133.0
module DECODE(
  input         clock,
                reset,
                io_DECODE_en_in,
  input  [31:0] io_read_readMEM1_result_in_data,
  input         io_fwd_X0_en_in,
  input  [31:0] io_fwd_X0_val_in,
                io_readX0_result_in_data,
  output        io_readX0_result_in_enable,
  output [4:0]  io_readX0_result_in_address,
  input         io_read_DECODE_full_in_data,
                io_fwd_X1_en_in,
  input  [31:0] io_fwd_X1_val_in,
                io_readX1_result_in_data,
  output        io_readX1_result_in_enable,
  output [4:0]  io_readX1_result_in_address,
  input  [31:0] io_read_readMEM1_addr_in_data,
                io_read_writePC1_value_in_data,
  output [2:0]  io_read_bin_is_BEQ_is_BNE_is_BGE_is_BG_out_data,
  output        io_read_rs1_neq_0_out_data,
  output [31:0] io_read_readX0_result_out_data,
  output        io_read_rs2_neq_0_out_data,
  output [31:0] io_read_readX1_result_out_data,
                io_read_writePC1_value_0_out_data,
                io_read_readMEM1_addr_0_out_data,
                io_read_n204_out_data,
  output        io_read_is_JALRBNEBGEUBGEJALBLTUBEQBLT_out_data,
  output [1:0]  io_read_sel_writePC0_value_out_data,
  output [4:0]  io_read_sel_readMEM0_addr_out_data,
  output [31:0] io_read_readMEM0_addr_out_data,
  output [4:0]  io_read_rs2_out_data,
  output        io_read_is_S_out_data,
  output [1:0]  io_read_sel_writeMEM0_words_out_data,
  output        io_read_not_is_not_none_out_data,
  output [2:0]  io_read_sel_writeX0_value_out_data,
  output [1:0]  io_read_sel_readMEM0_words_out_data,
  output        io_read_is_L_out_data,
                io_read_writeX0_enable_out_data,
  output [4:0]  io_read_rd_out_data,
                io_rs1_out,
                io_readX1_addr_out,
  output        io_readX0_enable_out,
                io_readX1_enable_out
);

  reg  [4:0]       rd;
  reg  [4:0]       rs2;
  reg  [31:0]      readMEM0_addr;
  reg              rs1_neq_0;
  reg              rs2_neq_0;
  reg  [31:0]      n204;
  reg              writeX0_enable;
  reg              is_JALRBNEBGEUBGEJALBLTUBEQBLT;
  reg              is_S;
  reg              is_L;
  reg  [2:0]       bin_is_BEQ_is_BNE_is_BGE_is_BG;
  reg  [1:0]       sel_writePC0_value;
  reg  [1:0]       sel_readMEM0_words;
  reg  [1:0]       sel_writeMEM0_words;
  reg  [2:0]       sel_writeX0_value;
  reg  [4:0]       sel_readMEM0_addr;
  reg              not_is_not_none;
  reg  [31:0]      readX0_result;
  reg  [31:0]      readX1_result;
  reg  [31:0]      readMEM1_addr;
  reg  [31:0]      writePC1_value;
  wire [9:0]       _GEN =
    {io_read_readMEM1_result_in_data[14:12], io_read_readMEM1_result_in_data[6:0]};
  wire             is_BNE = _GEN == 10'hE3;
  wire             is_BGEU = _GEN == 10'h3E3;
  wire             is_BGE = _GEN == 10'h2E3;
  wire             is_BLTU = _GEN == 10'h363;
  wire             is_BEQ = _GEN == 10'h63;
  wire             is_BLT = _GEN == 10'h263;
  wire             is_SH = _GEN == 10'hA3;
  wire             is_SB = _GEN == 10'h23;
  wire             is_SW = _GEN == 10'h123;
  wire             is_LH = _GEN == 10'h83;
  wire             a4_hi = _GEN == 10'h67;
  wire             is_SLTI = _GEN == 10'h113;
  wire             is_LB = _GEN == 10'h3;
  wire             is_ANDI = _GEN == 10'h393;
  wire             is_SLTIU = _GEN == 10'h193;
  wire             is_XORI = _GEN == 10'h213;
  wire             is_LHU = _GEN == 10'h283;
  wire             is_LW = _GEN == 10'h103;
  wire             is_LBU = _GEN == 10'h203;
  wire             is_ADDI = _GEN == 10'h13;
  wire             is_ORI = _GEN == 10'h313;
  wire [16:0]      _GEN_0 =
    {io_read_readMEM1_result_in_data[31:25],
     io_read_readMEM1_result_in_data[14:12],
     io_read_readMEM1_result_in_data[6:0]};
  wire             is_SRA = _GEN_0 == 17'h82B3;
  wire             is_SLT = _GEN_0 == 17'h133;
  wire             is_XOR = _GEN_0 == 17'h233;
  wire             is_SRLI = _GEN_0 == 17'h293;
  wire             is_SLL = _GEN_0 == 17'hB3;
  wire             is_SRL = _GEN_0 == 17'h2B3;
  wire             is_OR = _GEN_0 == 17'h333;
  wire             is_SLLI = _GEN_0 == 17'h93;
  wire             is_SUB = _GEN_0 == 17'h8033;
  wire             is_SLTU = _GEN_0 == 17'h1B3;
  wire             is_AND = _GEN_0 == 17'h3B3;
  wire             is_ADD = _GEN_0 == 17'h33;
  wire             is_SRAI = _GEN_0 == 17'h8293;
  wire             readX0_enable =
    (|(io_read_readMEM1_result_in_data[19:15]))
    & (is_LB | is_SRA | is_LHU | is_LBU | is_ORI | is_BLTU | is_SLT | is_XOR | is_BNE
       | is_SLTI | is_SRLI | is_LW | is_BEQ | is_SB | is_SLL | a4_hi | is_SRL | is_BGEU
       | is_BGE | is_ANDI | is_XORI | is_OR | is_SH | is_BLT | is_LH | is_SLLI | is_SUB
       | is_SLTIU | is_SLTU | is_AND | is_ADD | is_ADDI | is_SW | is_SRAI);
  wire             readX1_enable =
    (|(io_read_readMEM1_result_in_data[24:20]))
    & (is_SRL | is_BGEU | is_BGE | is_SRA | is_OR | is_SH | is_BLTU | is_BLT | is_SLT
       | is_XOR | is_BNE | is_SUB | is_SLTU | is_AND | is_ADD | is_SLL | is_SB | is_BEQ
       | is_SW);
  wire [31:0]      writeX0_value = {io_read_readMEM1_result_in_data[31:12], 12'h0};
  wire             sig_147 = is_SH | is_SB | is_SW;
  wire             is_JAL = io_read_readMEM1_result_in_data[6:0] == 7'h6F;
  wire             is_AUIPC = io_read_readMEM1_result_in_data[6:0] == 7'h17;
  wire [19:0]      _GEN_1 = {20{io_read_readMEM1_result_in_data[31]}};
  wire             is_LUI = io_read_readMEM1_result_in_data[6:0] == 7'h37;
  wire             sig_214 = is_LH | is_LB | is_LHU | is_LW | is_LBU;
  wire [2:0]       _a3_T_2 = {a4_hi, is_JAL, is_BLTU} | {is_BGEU, is_BGE, is_BNE};
  wire             _a7_T_21 =
    is_SRL | a4_hi | is_LUI | is_JAL | is_ANDI | is_SRA | is_XORI | is_OR | is_ORI
    | is_SLT | is_SLLI | is_XOR | is_SLTI | is_SUB | is_SLTIU | is_SLTU | is_SRLI | is_AND
    | is_ADD | is_AUIPC | is_ADDI | is_SLL | is_SRAI;
  wire [2:0]       _a7_T_24 = {2'h0, _a7_T_21} | {is_LHU, is_LH, is_LBU};
  wire             _a8_T = a4_hi | is_JAL;
  wire [14:0]      _a8_T_3 =
    {8'h0, _a8_T, is_SRAI, is_SRLI, is_SLLI, is_LUI, is_AUIPC, is_SLTIU}
    | {is_XORI,
       is_ORI,
       is_ANDI,
       is_ADDI,
       is_SRA,
       is_SRL,
       is_SLL,
       is_SLTU,
       is_SLT,
       is_XOR,
       is_OR,
       is_AND,
       is_SUB,
       is_ADD,
       sig_214};
  wire [6:0]       _a8_T_5 = _a8_T_3[14:8] | _a8_T_3[6:0];
  wire [2:0]       _a8_T_7 = _a8_T_5[6:4] | _a8_T_5[2:0];
  wire [7:0][31:0] _GEN_2 =
    {{32'h0},
     {32'h0},
     {32'h0},
     {{{20{io_read_readMEM1_result_in_data[31]}},
       io_read_readMEM1_result_in_data[7],
       io_read_readMEM1_result_in_data[30:25],
       io_read_readMEM1_result_in_data[11:8],
       1'h0}},
     {{_GEN_1,
       io_read_readMEM1_result_in_data[31:25],
       io_read_readMEM1_result_in_data[11:7]}},
     {{{12{io_read_readMEM1_result_in_data[31]}},
       io_read_readMEM1_result_in_data[19:12],
       io_read_readMEM1_result_in_data[20],
       io_read_readMEM1_result_in_data[30:21],
       1'h0}},
     {writeX0_value},
     {{_GEN_1, io_read_readMEM1_result_in_data[31:20]}}};
  always @(posedge clock) begin
    if (reset) begin
      rd <= 5'h0;
      rs2 <= 5'h0;
      readMEM0_addr <= 32'h0;
      rs1_neq_0 <= 1'h0;
      rs2_neq_0 <= 1'h0;
      n204 <= 32'h0;
      writeX0_enable <= 1'h0;
      is_JALRBNEBGEUBGEJALBLTUBEQBLT <= 1'h0;
      is_S <= 1'h0;
      is_L <= 1'h0;
      bin_is_BEQ_is_BNE_is_BGE_is_BG <= 3'h0;
      sel_writePC0_value <= 2'h0;
      sel_readMEM0_words <= 2'h0;
      sel_writeMEM0_words <= 2'h0;
      sel_writeX0_value <= 3'h0;
      sel_readMEM0_addr <= 5'h0;
      not_is_not_none <= 1'h0;
      readX0_result <= 32'h0;
      readX1_result <= 32'h0;
      readMEM1_addr <= 32'h0;
      writePC1_value <= 32'h0;
    end
    else if (io_DECODE_en_in) begin
      rd <= io_read_readMEM1_result_in_data[11:7];
      rs2 <= io_read_readMEM1_result_in_data[24:20];
      readMEM0_addr <= writeX0_value;
      rs1_neq_0 <= |(io_read_readMEM1_result_in_data[19:15]);
      rs2_neq_0 <= |(io_read_readMEM1_result_in_data[24:20]);
      n204 <=
        _GEN_2[{is_BNE | is_BGEU | is_BGE | is_BLTU | is_BEQ | is_BLT,
                |{sig_147, is_JAL},
                sig_147 | is_AUIPC}];
      writeX0_enable <=
        (|(io_read_readMEM1_result_in_data[11:7]))
        & (is_LB | is_JAL | is_SRA | is_LHU | is_LBU | is_ORI | is_SLT | is_XOR | is_SLTI
           | is_SRLI | is_LW | is_SLL | is_SRL | a4_hi | is_LUI | is_ANDI | is_XORI
           | is_OR | is_LH | is_SLLI | is_SUB | is_SLTIU | is_SLTU | is_AND | is_ADD
           | is_AUIPC | is_ADDI | is_SRAI);
      is_JALRBNEBGEUBGEJALBLTUBEQBLT <=
        a4_hi | is_BNE | is_BGEU | is_BGE | is_JAL | is_BLTU | is_BEQ | is_BLT;
      is_S <= sig_147;
      is_L <= sig_214;
      bin_is_BEQ_is_BNE_is_BGE_is_BG <=
        {|{a4_hi, is_JAL, is_BLTU, is_BLT}, |(_a3_T_2[2:1]), _a3_T_2[2] | _a3_T_2[0]};
      sel_writePC0_value <= {a4_hi, is_JAL};
      sel_readMEM0_words <= {is_LH | is_LHU, is_LW};
      sel_writeMEM0_words <= {is_SW, is_SH};
      sel_writeX0_value <=
        {|{_a7_T_21, is_LW}, |(_a7_T_24[2:1]), _a7_T_24[2] | _a7_T_24[0]};
      sel_readMEM0_addr <=
        {|{_a8_T, is_SRAI, is_SRLI, is_SLLI, is_LUI, is_AUIPC, is_SLTIU, is_SLTI},
         |(_a8_T_3[14:7]),
         |(_a8_T_5[6:3]),
         |(_a8_T_7[2:1]),
         _a8_T_7[2] | _a8_T_7[0]};
      not_is_not_none <=
        ~(is_ADD | is_SUB | is_AND | is_OR | is_XOR | is_SLT | is_SLTU | is_SLL | is_SRL
          | is_SRA | is_ADDI | is_ANDI | is_ORI | is_XORI | is_SLTI | is_SLTIU | is_AUIPC
          | is_LUI | is_LB | is_LBU | is_LH | is_LHU | is_LW | is_SB | is_SH | is_SW
          | is_BEQ | is_BNE | is_BGE | is_BGEU | is_BLT | is_BLTU | is_JAL | a4_hi
          | is_SLLI | is_SRLI | is_SRAI | io_read_readMEM1_result_in_data == 32'h73
          | io_read_readMEM1_result_in_data == 32'h100073);
      readX0_result <= io_fwd_X0_en_in ? io_fwd_X0_val_in : io_readX0_result_in_data;
      readX1_result <= io_fwd_X1_en_in ? io_fwd_X1_val_in : io_readX1_result_in_data;
      readMEM1_addr <= io_read_readMEM1_addr_in_data;
      writePC1_value <= io_read_writePC1_value_in_data;
    end
  end // always @(posedge)
  assign io_readX0_result_in_enable =
    io_read_DECODE_full_in_data & readX0_enable & ~io_fwd_X0_en_in;
  assign io_readX0_result_in_address = io_read_readMEM1_result_in_data[19:15];
  assign io_readX1_result_in_enable =
    io_read_DECODE_full_in_data & readX1_enable & ~io_fwd_X1_en_in;
  assign io_readX1_result_in_address = io_read_readMEM1_result_in_data[24:20];
  assign io_read_bin_is_BEQ_is_BNE_is_BGE_is_BG_out_data = bin_is_BEQ_is_BNE_is_BGE_is_BG;
  assign io_read_rs1_neq_0_out_data = rs1_neq_0;
  assign io_read_readX0_result_out_data = readX0_result;
  assign io_read_rs2_neq_0_out_data = rs2_neq_0;
  assign io_read_readX1_result_out_data = readX1_result;
  assign io_read_writePC1_value_0_out_data = writePC1_value;
  assign io_read_readMEM1_addr_0_out_data = readMEM1_addr;
  assign io_read_n204_out_data = n204;
  assign io_read_is_JALRBNEBGEUBGEJALBLTUBEQBLT_out_data = is_JALRBNEBGEUBGEJALBLTUBEQBLT;
  assign io_read_sel_writePC0_value_out_data = sel_writePC0_value;
  assign io_read_sel_readMEM0_addr_out_data = sel_readMEM0_addr;
  assign io_read_readMEM0_addr_out_data = readMEM0_addr;
  assign io_read_rs2_out_data = rs2;
  assign io_read_is_S_out_data = is_S;
  assign io_read_sel_writeMEM0_words_out_data = sel_writeMEM0_words;
  assign io_read_not_is_not_none_out_data = not_is_not_none;
  assign io_read_sel_writeX0_value_out_data = sel_writeX0_value;
  assign io_read_sel_readMEM0_words_out_data = sel_readMEM0_words;
  assign io_read_is_L_out_data = is_L;
  assign io_read_writeX0_enable_out_data = writeX0_enable;
  assign io_read_rd_out_data = rd;
  assign io_rs1_out = io_read_readMEM1_result_in_data[19:15];
  assign io_readX1_addr_out = io_read_readMEM1_result_in_data[24:20];
  assign io_readX0_enable_out = readX0_enable;
  assign io_readX1_enable_out = readX1_enable;
endmodule
