// Generated by CIRCT firtool-1.133.0
module DECODE(
  input         clock,
                reset,
  input  [31:0] io_read_readMEM1_result_in_data,
  input         io_DECODE_en_in,
                io_fwd_X0_en_in,
  input  [31:0] io_fwd_X0_val_in,
                io_readX0_result_in_data,
  output        io_readX0_result_in_enable,
  output [4:0]  io_readX0_result_in_address,
  input         io_read_DECODE_full_in_data,
                io_fwd_X1_en_in,
  input  [31:0] io_fwd_X1_val_in,
                io_readX1_result_in_data,
  output        io_readX1_result_in_enable,
  output [4:0]  io_readX1_result_in_address,
  input  [31:0] io_read_readMEM1_addr_in_data,
                io_read_writePC1_value_in_data,
  output [2:0]  io_read_n248_out_data,
  output        io_read_rs1_neq_0_out_data,
  output [31:0] io_read_readX0_result_out_data,
  output        io_read_rs2_neq_0_out_data,
  output [31:0] io_read_readX1_result_out_data,
                io_read_writePC1_value_0_out_data,
                io_read_readMEM1_addr_0_out_data,
                io_read_n204_out_data,
  output        io_read_is_JALRBEQJALBLTUBGEUBGEBLTBNE_out_data,
  output [1:0]  io_read_bin_writePC0_value_out_data,
  output [4:0]  io_read_sel_readMEM0_addr_out_data,
  output [31:0] io_read_readMEM0_addr_out_data,
  output [4:0]  io_read_rs2_out_data,
  output        io_read_is_S_out_data,
  output [1:0]  io_read_sel_writeMEM0_words_out_data,
  output        io_read_invalid_insn_out_data,
  output [2:0]  io_read_bin_writeX0_value_out_data,
  output [1:0]  io_read_bin_readMEM0_words_out_data,
  output        io_read_is_L_out_data,
                io_read_writeX0_enable_out_data,
  output [4:0]  io_read_rd_out_data,
                io_rs1_out,
                io_readX1_addr_out,
  output        io_readX0_enable_out,
                io_readX1_enable_out
);

  reg  [4:0]       rd;
  reg  [4:0]       rs2;
  reg  [31:0]      readMEM0_addr;
  reg              rs1_neq_0;
  reg              rs2_neq_0;
  reg  [31:0]      n204;
  reg              writeX0_enable;
  reg              is_JALRBEQJALBLTUBGEUBGEBLTBNE;
  reg              is_S;
  reg              is_L;
  reg  [2:0]       n248;
  reg  [1:0]       bin_writePC0_value;
  reg  [1:0]       bin_readMEM0_words;
  reg  [1:0]       sel_writeMEM0_words;
  reg  [2:0]       bin_writeX0_value;
  reg  [4:0]       sel_readMEM0_addr;
  reg              invalid_insn;
  reg  [31:0]      readX0_result;
  reg  [31:0]      readX1_result;
  reg  [31:0]      readMEM1_addr;
  reg  [31:0]      writePC1_value;
  wire [29:0]      dec_output_invInputs = ~(io_read_readMEM1_result_in_data[31:2]);
  wire [7:0]       _dec_output_andMatrixOutputs_T =
    {io_read_readMEM1_result_in_data[0],
     io_read_readMEM1_result_in_data[1],
     dec_output_invInputs[0],
     dec_output_invInputs[1],
     dec_output_invInputs[2],
     dec_output_invInputs[3],
     dec_output_invInputs[4],
     dec_output_invInputs[11]};
  wire [7:0]       _dec_output_andMatrixOutputs_T_1 =
    {io_read_readMEM1_result_in_data[0],
     io_read_readMEM1_result_in_data[1],
     dec_output_invInputs[0],
     dec_output_invInputs[1],
     dec_output_invInputs[3],
     dec_output_invInputs[4],
     dec_output_invInputs[10],
     dec_output_invInputs[11]};
  wire [7:0]       _dec_output_andMatrixOutputs_T_2 =
    {io_read_readMEM1_result_in_data[0],
     io_read_readMEM1_result_in_data[1],
     dec_output_invInputs[0],
     dec_output_invInputs[1],
     dec_output_invInputs[2],
     dec_output_invInputs[4],
     dec_output_invInputs[10],
     dec_output_invInputs[12]};
  wire [8:0]       _dec_output_andMatrixOutputs_T_9 =
    {io_read_readMEM1_result_in_data[0],
     io_read_readMEM1_result_in_data[1],
     dec_output_invInputs[0],
     dec_output_invInputs[1],
     dec_output_invInputs[2],
     io_read_readMEM1_result_in_data[5],
     dec_output_invInputs[4],
     dec_output_invInputs[10],
     dec_output_invInputs[12]};
  wire [7:0]       _dec_output_andMatrixOutputs_T_10 =
    {io_read_readMEM1_result_in_data[0],
     io_read_readMEM1_result_in_data[1],
     dec_output_invInputs[0],
     dec_output_invInputs[1],
     dec_output_invInputs[2],
     io_read_readMEM1_result_in_data[5],
     dec_output_invInputs[11],
     dec_output_invInputs[12]};
  wire [15:0]      _dec_output_andMatrixOutputs_T_12 =
    {io_read_readMEM1_result_in_data[0],
     io_read_readMEM1_result_in_data[1],
     dec_output_invInputs[0],
     dec_output_invInputs[1],
     io_read_readMEM1_result_in_data[4],
     io_read_readMEM1_result_in_data[5],
     dec_output_invInputs[4],
     dec_output_invInputs[10],
     dec_output_invInputs[11],
     dec_output_invInputs[12],
     dec_output_invInputs[23],
     dec_output_invInputs[24],
     dec_output_invInputs[25],
     dec_output_invInputs[26],
     dec_output_invInputs[27],
     dec_output_invInputs[29]};
  wire [13:0]      _dec_output_andMatrixOutputs_T_13 =
    {io_read_readMEM1_result_in_data[0],
     io_read_readMEM1_result_in_data[1],
     dec_output_invInputs[0],
     dec_output_invInputs[1],
     io_read_readMEM1_result_in_data[4],
     io_read_readMEM1_result_in_data[5],
     dec_output_invInputs[4],
     dec_output_invInputs[23],
     dec_output_invInputs[24],
     dec_output_invInputs[25],
     dec_output_invInputs[26],
     dec_output_invInputs[27],
     dec_output_invInputs[28],
     dec_output_invInputs[29]};
  wire [8:0]       _dec_output_andMatrixOutputs_T_17 =
    {io_read_readMEM1_result_in_data[0],
     io_read_readMEM1_result_in_data[1],
     dec_output_invInputs[1],
     dec_output_invInputs[2],
     io_read_readMEM1_result_in_data[5],
     io_read_readMEM1_result_in_data[6],
     dec_output_invInputs[10],
     dec_output_invInputs[11],
     dec_output_invInputs[12]};
  wire [14:0]      _dec_output_andMatrixOutputs_T_22 =
    {io_read_readMEM1_result_in_data[0],
     io_read_readMEM1_result_in_data[1],
     dec_output_invInputs[0],
     dec_output_invInputs[1],
     io_read_readMEM1_result_in_data[4],
     dec_output_invInputs[4],
     io_read_readMEM1_result_in_data[12],
     dec_output_invInputs[11],
     dec_output_invInputs[23],
     dec_output_invInputs[24],
     dec_output_invInputs[25],
     dec_output_invInputs[26],
     dec_output_invInputs[27],
     dec_output_invInputs[28],
     dec_output_invInputs[29]};
  wire [7:0]       _dec_output_andMatrixOutputs_T_30 =
    {io_read_readMEM1_result_in_data[0],
     io_read_readMEM1_result_in_data[1],
     dec_output_invInputs[0],
     dec_output_invInputs[1],
     io_read_readMEM1_result_in_data[4],
     dec_output_invInputs[3],
     dec_output_invInputs[4],
     io_read_readMEM1_result_in_data[13]};
  wire [7:0]       _dec_output_andMatrixOutputs_T_40 =
    {io_read_readMEM1_result_in_data[0],
     io_read_readMEM1_result_in_data[1],
     dec_output_invInputs[0],
     dec_output_invInputs[1],
     dec_output_invInputs[2],
     io_read_readMEM1_result_in_data[5],
     io_read_readMEM1_result_in_data[6],
     io_read_readMEM1_result_in_data[14]};
  wire [14:0]      _dec_output_andMatrixOutputs_T_42 =
    {io_read_readMEM1_result_in_data[0],
     io_read_readMEM1_result_in_data[1],
     dec_output_invInputs[0],
     dec_output_invInputs[1],
     io_read_readMEM1_result_in_data[4],
     dec_output_invInputs[4],
     io_read_readMEM1_result_in_data[12],
     dec_output_invInputs[11],
     io_read_readMEM1_result_in_data[14],
     dec_output_invInputs[23],
     dec_output_invInputs[24],
     dec_output_invInputs[25],
     dec_output_invInputs[26],
     dec_output_invInputs[27],
     dec_output_invInputs[29]};
  wire [15:0]      _dec_output_andMatrixOutputs_T_45 =
    {io_read_readMEM1_result_in_data[0],
     io_read_readMEM1_result_in_data[1],
     dec_output_invInputs[0],
     dec_output_invInputs[1],
     io_read_readMEM1_result_in_data[4],
     io_read_readMEM1_result_in_data[5],
     dec_output_invInputs[4],
     io_read_readMEM1_result_in_data[12],
     dec_output_invInputs[11],
     io_read_readMEM1_result_in_data[14],
     dec_output_invInputs[23],
     dec_output_invInputs[24],
     dec_output_invInputs[25],
     dec_output_invInputs[26],
     dec_output_invInputs[27],
     dec_output_invInputs[29]};
  wire [4:0]       rs1 = io_read_readMEM1_result_in_data[19:15];
  wire [4:0]       readX1_addr = io_read_readMEM1_result_in_data[24:20];
  wire             readX0_enable =
    (|rs1)
    & (|{&_dec_output_andMatrixOutputs_T,
         &_dec_output_andMatrixOutputs_T_1,
         &_dec_output_andMatrixOutputs_T_2,
         &_dec_output_andMatrixOutputs_T_10,
         &_dec_output_andMatrixOutputs_T_12,
         &_dec_output_andMatrixOutputs_T_13,
         &_dec_output_andMatrixOutputs_T_17,
         &_dec_output_andMatrixOutputs_T_22,
         &_dec_output_andMatrixOutputs_T_30,
         &_dec_output_andMatrixOutputs_T_40,
         &_dec_output_andMatrixOutputs_T_42});
  wire [31:0]      sig_79 = io_fwd_X0_en_in ? io_fwd_X0_val_in : io_readX0_result_in_data;
  wire             readX1_enable =
    (|readX1_addr)
    & (|{&_dec_output_andMatrixOutputs_T_9,
         &_dec_output_andMatrixOutputs_T_10,
         &_dec_output_andMatrixOutputs_T_12,
         &_dec_output_andMatrixOutputs_T_13,
         &_dec_output_andMatrixOutputs_T_40,
         &_dec_output_andMatrixOutputs_T_45});
  wire [31:0]      sig_85 = io_fwd_X1_en_in ? io_fwd_X1_val_in : io_readX1_result_in_data;
  wire [8:0]       _dec_output_andMatrixOutputs_T_4 =
    {io_read_readMEM1_result_in_data[0],
     io_read_readMEM1_result_in_data[1],
     dec_output_invInputs[0],
     dec_output_invInputs[1],
     dec_output_invInputs[2],
     dec_output_invInputs[3],
     dec_output_invInputs[4],
     dec_output_invInputs[10],
     dec_output_invInputs[12]};
  wire [7:0]       _dec_output_andMatrixOutputs_T_5 =
    {io_read_readMEM1_result_in_data[0],
     io_read_readMEM1_result_in_data[1],
     dec_output_invInputs[0],
     dec_output_invInputs[1],
     io_read_readMEM1_result_in_data[4],
     dec_output_invInputs[3],
     dec_output_invInputs[4],
     dec_output_invInputs[10]};
  wire [8:0]       _dec_output_andMatrixOutputs_T_6 =
    {io_read_readMEM1_result_in_data[0],
     io_read_readMEM1_result_in_data[1],
     dec_output_invInputs[0],
     dec_output_invInputs[1],
     io_read_readMEM1_result_in_data[4],
     dec_output_invInputs[3],
     dec_output_invInputs[4],
     dec_output_invInputs[10],
     dec_output_invInputs[11]};
  wire [5:0]       _dec_output_andMatrixOutputs_T_7 =
    {io_read_readMEM1_result_in_data[0],
     io_read_readMEM1_result_in_data[1],
     io_read_readMEM1_result_in_data[2],
     dec_output_invInputs[1],
     io_read_readMEM1_result_in_data[4],
     dec_output_invInputs[4]};
  wire [8:0]       _dec_output_andMatrixOutputs_T_11 =
    {io_read_readMEM1_result_in_data[0],
     io_read_readMEM1_result_in_data[1],
     dec_output_invInputs[0],
     dec_output_invInputs[1],
     dec_output_invInputs[2],
     io_read_readMEM1_result_in_data[5],
     dec_output_invInputs[4],
     dec_output_invInputs[11],
     dec_output_invInputs[12]};
  wire [7:0]       _dec_output_andMatrixOutputs_T_16 =
    {io_read_readMEM1_result_in_data[0],
     io_read_readMEM1_result_in_data[1],
     dec_output_invInputs[0],
     dec_output_invInputs[1],
     dec_output_invInputs[2],
     io_read_readMEM1_result_in_data[5],
     io_read_readMEM1_result_in_data[6],
     dec_output_invInputs[11]};
  wire [9:0]       _dec_output_andMatrixOutputs_T_18 =
    {io_read_readMEM1_result_in_data[0],
     io_read_readMEM1_result_in_data[1],
     io_read_readMEM1_result_in_data[2],
     dec_output_invInputs[1],
     dec_output_invInputs[2],
     io_read_readMEM1_result_in_data[5],
     io_read_readMEM1_result_in_data[6],
     dec_output_invInputs[10],
     dec_output_invInputs[11],
     dec_output_invInputs[12]};
  wire [6:0]       _dec_output_andMatrixOutputs_T_19 =
    {io_read_readMEM1_result_in_data[0],
     io_read_readMEM1_result_in_data[1],
     io_read_readMEM1_result_in_data[2],
     io_read_readMEM1_result_in_data[3],
     dec_output_invInputs[2],
     io_read_readMEM1_result_in_data[5],
     io_read_readMEM1_result_in_data[6]};
  wire [8:0]       _dec_output_andMatrixOutputs_T_21 =
    {io_read_readMEM1_result_in_data[0],
     io_read_readMEM1_result_in_data[1],
     dec_output_invInputs[0],
     dec_output_invInputs[1],
     dec_output_invInputs[2],
     dec_output_invInputs[3],
     dec_output_invInputs[4],
     io_read_readMEM1_result_in_data[12],
     dec_output_invInputs[11]};
  wire [15:0]      _dec_output_andMatrixOutputs_T_23 =
    {io_read_readMEM1_result_in_data[0],
     io_read_readMEM1_result_in_data[1],
     dec_output_invInputs[0],
     dec_output_invInputs[1],
     io_read_readMEM1_result_in_data[4],
     dec_output_invInputs[3],
     dec_output_invInputs[4],
     io_read_readMEM1_result_in_data[12],
     dec_output_invInputs[11],
     dec_output_invInputs[23],
     dec_output_invInputs[24],
     dec_output_invInputs[25],
     dec_output_invInputs[26],
     dec_output_invInputs[27],
     dec_output_invInputs[28],
     dec_output_invInputs[29]};
  wire [15:0]      _dec_output_andMatrixOutputs_T_33 =
    {io_read_readMEM1_result_in_data[0],
     io_read_readMEM1_result_in_data[1],
     dec_output_invInputs[0],
     dec_output_invInputs[1],
     io_read_readMEM1_result_in_data[4],
     io_read_readMEM1_result_in_data[5],
     dec_output_invInputs[4],
     dec_output_invInputs[10],
     io_read_readMEM1_result_in_data[13],
     dec_output_invInputs[23],
     dec_output_invInputs[24],
     dec_output_invInputs[25],
     dec_output_invInputs[26],
     dec_output_invInputs[27],
     dec_output_invInputs[28],
     dec_output_invInputs[29]};
  wire [15:0]      _dec_output_andMatrixOutputs_T_43 =
    {io_read_readMEM1_result_in_data[0],
     io_read_readMEM1_result_in_data[1],
     dec_output_invInputs[0],
     dec_output_invInputs[1],
     io_read_readMEM1_result_in_data[4],
     dec_output_invInputs[3],
     dec_output_invInputs[4],
     io_read_readMEM1_result_in_data[12],
     dec_output_invInputs[11],
     io_read_readMEM1_result_in_data[14],
     dec_output_invInputs[23],
     dec_output_invInputs[24],
     dec_output_invInputs[25],
     dec_output_invInputs[26],
     dec_output_invInputs[27],
     dec_output_invInputs[29]};
  wire [8:0]       _dec_output_andMatrixOutputs_T_47 =
    {io_read_readMEM1_result_in_data[0],
     io_read_readMEM1_result_in_data[1],
     dec_output_invInputs[0],
     dec_output_invInputs[1],
     io_read_readMEM1_result_in_data[4],
     dec_output_invInputs[3],
     dec_output_invInputs[4],
     io_read_readMEM1_result_in_data[13],
     io_read_readMEM1_result_in_data[14]};
  wire [31:0]      writeX0_value = {io_read_readMEM1_result_in_data[31:12], 12'h0};
  wire [19:0]      _GEN = {20{io_read_readMEM1_result_in_data[31]}};
  wire [7:0][31:0] _GEN_0 =
    {{32'h0},
     {32'h0},
     {32'h0},
     {{{20{io_read_readMEM1_result_in_data[31]}},
       io_read_readMEM1_result_in_data[7],
       io_read_readMEM1_result_in_data[30:25],
       io_read_readMEM1_result_in_data[11:8],
       1'h0}},
     {{_GEN,
       io_read_readMEM1_result_in_data[31:25],
       io_read_readMEM1_result_in_data[11:7]}},
     {{{12{io_read_readMEM1_result_in_data[31]}},
       io_read_readMEM1_result_in_data[19:12],
       io_read_readMEM1_result_in_data[20],
       io_read_readMEM1_result_in_data[30:21],
       1'h0}},
     {writeX0_value},
     {{_GEN, io_read_readMEM1_result_in_data[31:20]}}};
  wire [4:0]       dec_bin_readMEM0_addr =
    {|{&_dec_output_andMatrixOutputs_T_7,
       &_dec_output_andMatrixOutputs_T_18,
       &_dec_output_andMatrixOutputs_T_19,
       &_dec_output_andMatrixOutputs_T_23,
       &{io_read_readMEM1_result_in_data[0],
         io_read_readMEM1_result_in_data[1],
         dec_output_invInputs[0],
         dec_output_invInputs[1],
         io_read_readMEM1_result_in_data[4],
         dec_output_invInputs[3],
         dec_output_invInputs[4],
         io_read_readMEM1_result_in_data[13],
         dec_output_invInputs[12]},
       &_dec_output_andMatrixOutputs_T_43},
     |{&_dec_output_andMatrixOutputs_T_6,
       &{io_read_readMEM1_result_in_data[0],
         io_read_readMEM1_result_in_data[1],
         dec_output_invInputs[0],
         dec_output_invInputs[1],
         io_read_readMEM1_result_in_data[4],
         io_read_readMEM1_result_in_data[5],
         dec_output_invInputs[4],
         io_read_readMEM1_result_in_data[12],
         dec_output_invInputs[12],
         dec_output_invInputs[23],
         dec_output_invInputs[24],
         dec_output_invInputs[25],
         dec_output_invInputs[26],
         dec_output_invInputs[27],
         dec_output_invInputs[28],
         dec_output_invInputs[29]},
       &_dec_output_andMatrixOutputs_T_45,
       &_dec_output_andMatrixOutputs_T_47},
     |{&_dec_output_andMatrixOutputs_T_6,
       &_dec_output_andMatrixOutputs_T_18,
       &_dec_output_andMatrixOutputs_T_19,
       &_dec_output_andMatrixOutputs_T_23,
       &_dec_output_andMatrixOutputs_T_33,
       &{io_read_readMEM1_result_in_data[0],
         io_read_readMEM1_result_in_data[1],
         dec_output_invInputs[0],
         dec_output_invInputs[1],
         io_read_readMEM1_result_in_data[4],
         io_read_readMEM1_result_in_data[5],
         dec_output_invInputs[4],
         dec_output_invInputs[10],
         io_read_readMEM1_result_in_data[14],
         dec_output_invInputs[23],
         dec_output_invInputs[24],
         dec_output_invInputs[25],
         dec_output_invInputs[26],
         dec_output_invInputs[27],
         dec_output_invInputs[28],
         dec_output_invInputs[29]},
       &_dec_output_andMatrixOutputs_T_43,
       &_dec_output_andMatrixOutputs_T_47,
       &{io_read_readMEM1_result_in_data[0],
         io_read_readMEM1_result_in_data[1],
         dec_output_invInputs[0],
         dec_output_invInputs[1],
         io_read_readMEM1_result_in_data[4],
         io_read_readMEM1_result_in_data[5],
         dec_output_invInputs[4],
         io_read_readMEM1_result_in_data[13],
         io_read_readMEM1_result_in_data[14],
         dec_output_invInputs[23],
         dec_output_invInputs[24],
         dec_output_invInputs[25],
         dec_output_invInputs[26],
         dec_output_invInputs[27],
         dec_output_invInputs[28],
         dec_output_invInputs[29]}},
     |{&_dec_output_andMatrixOutputs_T_7,
       &_dec_output_andMatrixOutputs_T_12,
       &{io_read_readMEM1_result_in_data[0],
         io_read_readMEM1_result_in_data[1],
         dec_output_invInputs[0],
         dec_output_invInputs[1],
         io_read_readMEM1_result_in_data[4],
         io_read_readMEM1_result_in_data[5],
         dec_output_invInputs[4],
         dec_output_invInputs[10],
         dec_output_invInputs[12],
         dec_output_invInputs[23],
         dec_output_invInputs[24],
         dec_output_invInputs[25],
         dec_output_invInputs[26],
         dec_output_invInputs[27],
         dec_output_invInputs[28],
         dec_output_invInputs[29]},
       &_dec_output_andMatrixOutputs_T_18,
       &_dec_output_andMatrixOutputs_T_19,
       &{io_read_readMEM1_result_in_data[0],
         io_read_readMEM1_result_in_data[1],
         dec_output_invInputs[0],
         dec_output_invInputs[1],
         io_read_readMEM1_result_in_data[4],
         dec_output_invInputs[3],
         dec_output_invInputs[4],
         dec_output_invInputs[10],
         io_read_readMEM1_result_in_data[14]},
       &{io_read_readMEM1_result_in_data[0],
         io_read_readMEM1_result_in_data[1],
         dec_output_invInputs[0],
         dec_output_invInputs[1],
         io_read_readMEM1_result_in_data[4],
         io_read_readMEM1_result_in_data[5],
         dec_output_invInputs[4],
         dec_output_invInputs[11],
         io_read_readMEM1_result_in_data[14],
         dec_output_invInputs[23],
         dec_output_invInputs[24],
         dec_output_invInputs[25],
         dec_output_invInputs[26],
         dec_output_invInputs[27],
         dec_output_invInputs[28],
         dec_output_invInputs[29]},
       &{io_read_readMEM1_result_in_data[0],
         io_read_readMEM1_result_in_data[1],
         dec_output_invInputs[0],
         dec_output_invInputs[1],
         io_read_readMEM1_result_in_data[4],
         dec_output_invInputs[4],
         io_read_readMEM1_result_in_data[12],
         dec_output_invInputs[11],
         io_read_readMEM1_result_in_data[14],
         dec_output_invInputs[23],
         dec_output_invInputs[24],
         dec_output_invInputs[25],
         dec_output_invInputs[26],
         dec_output_invInputs[27],
         io_read_readMEM1_result_in_data[30],
         dec_output_invInputs[29]}},
     |{&_dec_output_andMatrixOutputs_T,
       &_dec_output_andMatrixOutputs_T_4,
       &{io_read_readMEM1_result_in_data[0],
         io_read_readMEM1_result_in_data[1],
         io_read_readMEM1_result_in_data[2],
         dec_output_invInputs[1],
         io_read_readMEM1_result_in_data[4],
         io_read_readMEM1_result_in_data[5],
         dec_output_invInputs[4]},
       &_dec_output_andMatrixOutputs_T_18,
       &_dec_output_andMatrixOutputs_T_19,
       &{io_read_readMEM1_result_in_data[0],
         io_read_readMEM1_result_in_data[1],
         dec_output_invInputs[0],
         dec_output_invInputs[1],
         io_read_readMEM1_result_in_data[4],
         io_read_readMEM1_result_in_data[5],
         dec_output_invInputs[4],
         io_read_readMEM1_result_in_data[12],
         dec_output_invInputs[11],
         dec_output_invInputs[12],
         dec_output_invInputs[23],
         dec_output_invInputs[24],
         dec_output_invInputs[25],
         dec_output_invInputs[26],
         dec_output_invInputs[27],
         dec_output_invInputs[28],
         dec_output_invInputs[29]},
       &_dec_output_andMatrixOutputs_T_33,
       &{io_read_readMEM1_result_in_data[0],
         io_read_readMEM1_result_in_data[1],
         dec_output_invInputs[0],
         dec_output_invInputs[1],
         io_read_readMEM1_result_in_data[4],
         dec_output_invInputs[3],
         dec_output_invInputs[4],
         io_read_readMEM1_result_in_data[12],
         io_read_readMEM1_result_in_data[13]},
       &{io_read_readMEM1_result_in_data[0],
         io_read_readMEM1_result_in_data[1],
         dec_output_invInputs[0],
         dec_output_invInputs[1],
         dec_output_invInputs[3],
         dec_output_invInputs[4],
         dec_output_invInputs[10],
         dec_output_invInputs[11],
         io_read_readMEM1_result_in_data[14]},
       &{io_read_readMEM1_result_in_data[0],
         io_read_readMEM1_result_in_data[1],
         dec_output_invInputs[0],
         dec_output_invInputs[1],
         io_read_readMEM1_result_in_data[4],
         dec_output_invInputs[3],
         dec_output_invInputs[4],
         io_read_readMEM1_result_in_data[12],
         dec_output_invInputs[11],
         io_read_readMEM1_result_in_data[14],
         dec_output_invInputs[23],
         dec_output_invInputs[24],
         dec_output_invInputs[25],
         dec_output_invInputs[26],
         dec_output_invInputs[27],
         dec_output_invInputs[28],
         dec_output_invInputs[29]},
       &{io_read_readMEM1_result_in_data[0],
         io_read_readMEM1_result_in_data[1],
         dec_output_invInputs[0],
         dec_output_invInputs[1],
         io_read_readMEM1_result_in_data[4],
         io_read_readMEM1_result_in_data[5],
         dec_output_invInputs[4],
         dec_output_invInputs[10],
         dec_output_invInputs[11],
         dec_output_invInputs[12],
         dec_output_invInputs[23],
         dec_output_invInputs[24],
         dec_output_invInputs[25],
         dec_output_invInputs[26],
         dec_output_invInputs[27],
         io_read_readMEM1_result_in_data[30],
         dec_output_invInputs[29]},
       &{io_read_readMEM1_result_in_data[0],
         io_read_readMEM1_result_in_data[1],
         dec_output_invInputs[0],
         dec_output_invInputs[1],
         io_read_readMEM1_result_in_data[4],
         io_read_readMEM1_result_in_data[5],
         dec_output_invInputs[4],
         io_read_readMEM1_result_in_data[12],
         dec_output_invInputs[11],
         io_read_readMEM1_result_in_data[14],
         dec_output_invInputs[23],
         dec_output_invInputs[24],
         dec_output_invInputs[25],
         dec_output_invInputs[26],
         dec_output_invInputs[27],
         io_read_readMEM1_result_in_data[30],
         dec_output_invInputs[29]}}};
  always @(posedge clock) begin
    if (reset) begin
      rd <= 5'h0;
      rs2 <= 5'h0;
      readMEM0_addr <= 32'h0;
      rs1_neq_0 <= 1'h0;
      rs2_neq_0 <= 1'h0;
      n204 <= 32'h0;
      writeX0_enable <= 1'h0;
      is_JALRBEQJALBLTUBGEUBGEBLTBNE <= 1'h0;
      is_S <= 1'h0;
      is_L <= 1'h0;
      n248 <= 3'h0;
      bin_writePC0_value <= 2'h0;
      bin_readMEM0_words <= 2'h0;
      sel_writeMEM0_words <= 2'h0;
      bin_writeX0_value <= 3'h0;
      sel_readMEM0_addr <= 5'h0;
      invalid_insn <= 1'h0;
      readX0_result <= 32'h0;
      readX1_result <= 32'h0;
      readMEM1_addr <= 32'h0;
      writePC1_value <= 32'h0;
    end
    else if (io_DECODE_en_in) begin
      rd <= io_read_readMEM1_result_in_data[11:7];
      rs2 <= io_read_readMEM1_result_in_data[24:20];
      readMEM0_addr <= writeX0_value;
      rs1_neq_0 <= |rs1;
      rs2_neq_0 <= |readX1_addr;
      n204 <=
        _GEN_0[{|{&_dec_output_andMatrixOutputs_T_16, &_dec_output_andMatrixOutputs_T_40},
                |{&_dec_output_andMatrixOutputs_T_9,
                  &_dec_output_andMatrixOutputs_T_11,
                  &_dec_output_andMatrixOutputs_T_19},
                |{&{io_read_readMEM1_result_in_data[0],
                    io_read_readMEM1_result_in_data[1],
                    io_read_readMEM1_result_in_data[2],
                    dec_output_invInputs[1],
                    io_read_readMEM1_result_in_data[4],
                    dec_output_invInputs[3],
                    dec_output_invInputs[4]},
                  &_dec_output_andMatrixOutputs_T_9,
                  &_dec_output_andMatrixOutputs_T_11}}];
      writeX0_enable <=
        (|(io_read_readMEM1_result_in_data[11:7]))
        & (|{&_dec_output_andMatrixOutputs_T,
             &_dec_output_andMatrixOutputs_T_1,
             &{io_read_readMEM1_result_in_data[0],
               io_read_readMEM1_result_in_data[1],
               dec_output_invInputs[0],
               dec_output_invInputs[1],
               dec_output_invInputs[3],
               dec_output_invInputs[4],
               dec_output_invInputs[10],
               dec_output_invInputs[12]},
             &_dec_output_andMatrixOutputs_T_7,
             &_dec_output_andMatrixOutputs_T_12,
             &_dec_output_andMatrixOutputs_T_13,
             &_dec_output_andMatrixOutputs_T_18,
             &_dec_output_andMatrixOutputs_T_19,
             &_dec_output_andMatrixOutputs_T_22,
             &_dec_output_andMatrixOutputs_T_30,
             &_dec_output_andMatrixOutputs_T_42});
      is_JALRBEQJALBLTUBGEUBGEBLTBNE <=
        |{&_dec_output_andMatrixOutputs_T_16,
          &_dec_output_andMatrixOutputs_T_17,
          &_dec_output_andMatrixOutputs_T_19,
          &_dec_output_andMatrixOutputs_T_40};
      is_S <= |{&_dec_output_andMatrixOutputs_T_9, &_dec_output_andMatrixOutputs_T_11};
      is_L <= |{&_dec_output_andMatrixOutputs_T, &_dec_output_andMatrixOutputs_T_4};
      n248 <=
        {|{&_dec_output_andMatrixOutputs_T_18,
           &_dec_output_andMatrixOutputs_T_19,
           &{io_read_readMEM1_result_in_data[0],
             io_read_readMEM1_result_in_data[1],
             dec_output_invInputs[0],
             dec_output_invInputs[1],
             dec_output_invInputs[2],
             io_read_readMEM1_result_in_data[5],
             io_read_readMEM1_result_in_data[6],
             dec_output_invInputs[10],
             io_read_readMEM1_result_in_data[14]}},
         |{&_dec_output_andMatrixOutputs_T_18,
           &_dec_output_andMatrixOutputs_T_19,
           &{io_read_readMEM1_result_in_data[0],
             io_read_readMEM1_result_in_data[1],
             dec_output_invInputs[0],
             dec_output_invInputs[1],
             dec_output_invInputs[2],
             io_read_readMEM1_result_in_data[5],
             io_read_readMEM1_result_in_data[6],
             io_read_readMEM1_result_in_data[12],
             io_read_readMEM1_result_in_data[14]}},
         |{&_dec_output_andMatrixOutputs_T_18,
           &{io_read_readMEM1_result_in_data[0],
             io_read_readMEM1_result_in_data[1],
             dec_output_invInputs[0],
             dec_output_invInputs[1],
             dec_output_invInputs[2],
             io_read_readMEM1_result_in_data[5],
             io_read_readMEM1_result_in_data[6],
             io_read_readMEM1_result_in_data[12],
             dec_output_invInputs[11],
             dec_output_invInputs[12]},
           &{io_read_readMEM1_result_in_data[0],
             io_read_readMEM1_result_in_data[1],
             dec_output_invInputs[0],
             dec_output_invInputs[1],
             dec_output_invInputs[2],
             io_read_readMEM1_result_in_data[5],
             io_read_readMEM1_result_in_data[6],
             io_read_readMEM1_result_in_data[13],
             io_read_readMEM1_result_in_data[14]}}};
      bin_writePC0_value <=
        {&_dec_output_andMatrixOutputs_T_18, &_dec_output_andMatrixOutputs_T_19};
      bin_readMEM0_words <=
        {&_dec_output_andMatrixOutputs_T_21,
         &{io_read_readMEM1_result_in_data[0],
           io_read_readMEM1_result_in_data[1],
           dec_output_invInputs[0],
           dec_output_invInputs[1],
           dec_output_invInputs[2],
           dec_output_invInputs[3],
           dec_output_invInputs[4],
           dec_output_invInputs[10],
           io_read_readMEM1_result_in_data[13],
           dec_output_invInputs[12]}};
      sel_writeMEM0_words <=
        {&{io_read_readMEM1_result_in_data[0],
           io_read_readMEM1_result_in_data[1],
           dec_output_invInputs[0],
           dec_output_invInputs[1],
           dec_output_invInputs[2],
           io_read_readMEM1_result_in_data[5],
           dec_output_invInputs[4],
           dec_output_invInputs[10],
           io_read_readMEM1_result_in_data[13],
           dec_output_invInputs[12]},
         &{io_read_readMEM1_result_in_data[0],
           io_read_readMEM1_result_in_data[1],
           dec_output_invInputs[0],
           dec_output_invInputs[1],
           dec_output_invInputs[2],
           io_read_readMEM1_result_in_data[5],
           dec_output_invInputs[4],
           io_read_readMEM1_result_in_data[12],
           dec_output_invInputs[11],
           dec_output_invInputs[12]}};
      bin_writeX0_value <=
        {|{&_dec_output_andMatrixOutputs_T_5,
           &_dec_output_andMatrixOutputs_T_7,
           &_dec_output_andMatrixOutputs_T_12,
           &_dec_output_andMatrixOutputs_T_13,
           &_dec_output_andMatrixOutputs_T_18,
           &_dec_output_andMatrixOutputs_T_19,
           &_dec_output_andMatrixOutputs_T_22,
           &{io_read_readMEM1_result_in_data[0],
             io_read_readMEM1_result_in_data[1],
             dec_output_invInputs[0],
             dec_output_invInputs[1],
             dec_output_invInputs[3],
             dec_output_invInputs[4],
             dec_output_invInputs[10],
             io_read_readMEM1_result_in_data[13],
             dec_output_invInputs[12]},
           &_dec_output_andMatrixOutputs_T_30,
           &_dec_output_andMatrixOutputs_T_42},
         &_dec_output_andMatrixOutputs_T_21,
         |{&_dec_output_andMatrixOutputs_T_5,
           &_dec_output_andMatrixOutputs_T_7,
           &_dec_output_andMatrixOutputs_T_12,
           &_dec_output_andMatrixOutputs_T_13,
           &_dec_output_andMatrixOutputs_T_18,
           &_dec_output_andMatrixOutputs_T_19,
           &_dec_output_andMatrixOutputs_T_22,
           &_dec_output_andMatrixOutputs_T_30,
           &{io_read_readMEM1_result_in_data[0],
             io_read_readMEM1_result_in_data[1],
             dec_output_invInputs[0],
             dec_output_invInputs[1],
             dec_output_invInputs[2],
             dec_output_invInputs[3],
             dec_output_invInputs[4],
             dec_output_invInputs[11],
             io_read_readMEM1_result_in_data[14]},
           &_dec_output_andMatrixOutputs_T_42}};
      sel_readMEM0_addr <= dec_bin_readMEM0_addr;
      invalid_insn <=
        {&_dec_output_andMatrixOutputs_T,
         &_dec_output_andMatrixOutputs_T_1,
         &_dec_output_andMatrixOutputs_T_2,
         &_dec_output_andMatrixOutputs_T_7,
         &_dec_output_andMatrixOutputs_T_10,
         &_dec_output_andMatrixOutputs_T_12,
         &_dec_output_andMatrixOutputs_T_13,
         &_dec_output_andMatrixOutputs_T_17,
         &_dec_output_andMatrixOutputs_T_19,
         &{io_read_readMEM1_result_in_data[0],
           io_read_readMEM1_result_in_data[1],
           dec_output_invInputs[0],
           dec_output_invInputs[1],
           io_read_readMEM1_result_in_data[4],
           io_read_readMEM1_result_in_data[5],
           io_read_readMEM1_result_in_data[6],
           dec_output_invInputs[5],
           dec_output_invInputs[6],
           dec_output_invInputs[7],
           dec_output_invInputs[8],
           dec_output_invInputs[9],
           dec_output_invInputs[10],
           dec_output_invInputs[11],
           dec_output_invInputs[12],
           dec_output_invInputs[13],
           dec_output_invInputs[14],
           dec_output_invInputs[15],
           dec_output_invInputs[16],
           dec_output_invInputs[17],
           dec_output_invInputs[19],
           dec_output_invInputs[20],
           dec_output_invInputs[21],
           dec_output_invInputs[22],
           dec_output_invInputs[23],
           dec_output_invInputs[24],
           dec_output_invInputs[25],
           dec_output_invInputs[26],
           dec_output_invInputs[27],
           dec_output_invInputs[28],
           dec_output_invInputs[29]},
         &_dec_output_andMatrixOutputs_T_22,
         &_dec_output_andMatrixOutputs_T_30,
         &_dec_output_andMatrixOutputs_T_40,
         &_dec_output_andMatrixOutputs_T_42} == 14'h0;
      readX0_result <= sig_79;
      readX1_result <= sig_85;
      readMEM1_addr <= io_read_readMEM1_addr_in_data;
      writePC1_value <= io_read_writePC1_value_in_data;
    end
  end // always @(posedge)
  assign io_readX0_result_in_enable =
    io_read_DECODE_full_in_data & readX0_enable & ~io_fwd_X0_en_in;
  assign io_readX0_result_in_address = rs1;
  assign io_readX1_result_in_enable =
    io_read_DECODE_full_in_data & readX1_enable & ~io_fwd_X1_en_in;
  assign io_readX1_result_in_address = readX1_addr;
  assign io_read_n248_out_data = n248;
  assign io_read_rs1_neq_0_out_data = rs1_neq_0;
  assign io_read_readX0_result_out_data = readX0_result;
  assign io_read_rs2_neq_0_out_data = rs2_neq_0;
  assign io_read_readX1_result_out_data = readX1_result;
  assign io_read_writePC1_value_0_out_data = writePC1_value;
  assign io_read_readMEM1_addr_0_out_data = readMEM1_addr;
  assign io_read_n204_out_data = n204;
  assign io_read_is_JALRBEQJALBLTUBGEUBGEBLTBNE_out_data = is_JALRBEQJALBLTUBGEUBGEBLTBNE;
  assign io_read_bin_writePC0_value_out_data = bin_writePC0_value;
  assign io_read_sel_readMEM0_addr_out_data = sel_readMEM0_addr;
  assign io_read_readMEM0_addr_out_data = readMEM0_addr;
  assign io_read_rs2_out_data = rs2;
  assign io_read_is_S_out_data = is_S;
  assign io_read_sel_writeMEM0_words_out_data = sel_writeMEM0_words;
  assign io_read_invalid_insn_out_data = invalid_insn;
  assign io_read_bin_writeX0_value_out_data = bin_writeX0_value;
  assign io_read_bin_readMEM0_words_out_data = bin_readMEM0_words;
  assign io_read_is_L_out_data = is_L;
  assign io_read_writeX0_enable_out_data = writeX0_enable;
  assign io_read_rd_out_data = rd;
  assign io_rs1_out = rs1;
  assign io_readX1_addr_out = readX1_addr;
  assign io_readX0_enable_out = readX0_enable;
  assign io_readX1_enable_out = readX1_enable;
endmodule

