// Generated by CIRCT firtool-1.133.0
module DECODE(
  input         clock,
                reset,
  input  [31:0] io_read_readMEM1_result_in_data,
  input         io_DECODE_en_in,
                io_fwd_X0_en_in,
  input  [31:0] io_fwd_X0_val_in,
                io_readX0_result_in_data,
  output        io_readX0_result_in_enable,
  output [4:0]  io_readX0_result_in_address,
  input         io_read_DECODE_full_in_data,
                io_fwd_X1_en_in,
  input  [31:0] io_fwd_X1_val_in,
                io_readX1_result_in_data,
  output        io_readX1_result_in_enable,
  output [4:0]  io_readX1_result_in_address,
  input  [31:0] io_read_readMEM1_addr_in_data,
                io_read_writePC1_value_in_data,
  output [2:0]  io_read_n248_out_data,
  output        io_read_rs1_neq_0_out_data,
  output [31:0] io_read_readX0_result_out_data,
  output        io_read_rs2_neq_0_out_data,
  output [31:0] io_read_readX1_result_out_data,
                io_read_writePC1_value_0_out_data,
                io_read_readMEM1_addr_0_out_data,
                io_read_n204_out_data,
  output        io_read_is_JALRBEQBLTBGEBGEUBNEJALBLTU_out_data,
  output [1:0]  io_read_bin_writePC0_value_out_data,
  output [4:0]  io_read_sel_readMEM0_addr_out_data,
  output [31:0] io_read_readMEM0_addr_out_data,
  output [4:0]  io_read_rs2_out_data,
  output        io_read_is_S_out_data,
  output [1:0]  io_read_sel_writeMEM0_words_out_data,
  output        io_read_invalid_insn_out_data,
  output [2:0]  io_read_bin_writeX0_value_out_data,
  output [1:0]  io_read_bin_readMEM0_words_out_data,
  output        io_read_is_L_out_data,
                io_read_writeX0_enable_out_data,
  output [4:0]  io_read_rd_out_data,
                io_rs1_out,
                io_readX1_addr_out,
  output        io_readX0_enable_out,
                io_readX1_enable_out
);

  reg  [4:0]       rd;
  reg  [4:0]       rs2;
  reg  [31:0]      readMEM0_addr;
  reg              rs1_neq_0;
  reg              rs2_neq_0;
  reg  [31:0]      n204;
  reg              writeX0_enable;
  reg              is_JALRBEQBLTBGEBGEUBNEJALBLTU;
  reg              is_S;
  reg              is_L;
  reg  [2:0]       n248;
  reg  [1:0]       bin_writePC0_value;
  reg  [1:0]       bin_readMEM0_words;
  reg  [1:0]       sel_writeMEM0_words;
  reg  [2:0]       bin_writeX0_value;
  reg  [4:0]       sel_readMEM0_addr;
  reg              invalid_insn;
  reg  [31:0]      readX0_result;
  reg  [31:0]      readX1_result;
  reg  [31:0]      readMEM1_addr;
  reg  [31:0]      writePC1_value;
  wire             _GEN = io_read_readMEM1_result_in_data[30:24] == 7'h13;
  wire             _GEN_0 = io_read_readMEM1_result_in_data[22:20] == 3'h4;
  wire             _GEN_1 = io_read_readMEM1_result_in_data[22:20] == 3'h1;
  wire             _GEN_2 = io_read_readMEM1_result_in_data[22:20] == 3'h5;
  wire             _GEN_3 = io_read_readMEM1_result_in_data[7:1] == 7'h20;
  wire             _GEN_4 = io_read_readMEM1_result_in_data[22:20] == 3'h6;
  wire             _GEN_5 = io_read_readMEM1_result_in_data[22:20] == 3'h2;
  wire             _GEN_6 = io_read_readMEM1_result_in_data[22:20] == 3'h3;
  wire             _GEN_7 =
    (&(io_read_readMEM1_result_in_data[22:20]))
    | ~(|(io_read_readMEM1_result_in_data[22:20])) | _GEN_4 | _GEN_5;
  wire             _GEN_8 =
    _GEN_0
    | (_GEN_1
         ? ~(|(io_read_readMEM1_result_in_data[7:1]))
         : _GEN_2
             ? ~(|(io_read_readMEM1_result_in_data[7:1])) | _GEN_3
             : _GEN_7 | _GEN_6);
  wire             _GEN_9 = io_read_readMEM1_result_in_data[30:24] == 7'h33;
  wire [9:0]       _GEN_10 =
    {io_read_readMEM1_result_in_data[22:20], io_read_readMEM1_result_in_data[7:1]};
  wire             _GEN_11 = _GEN_10 == 10'h80;
  wire             _GEN_12 = _GEN_10 == 10'h180;
  wire             _GEN_13 = _GEN_10 == 10'h200;
  wire             _GEN_14 = _GEN_10 == 10'h20;
  wire             _GEN_15 = _GEN_10 == 10'h280;
  wire             _GEN_16 = _GEN_10 == 10'h300;
  wire             _GEN_17 = _GEN_10 == 10'h0;
  wire             _GEN_18 = _GEN_10 == 10'h380;
  wire             _GEN_19 = _GEN_10 == 10'h100;
  wire             _GEN_20 = _GEN_10 == 10'h2A0;
  wire             _GEN_21 =
    _GEN_11 | _GEN_12 | _GEN_13 | _GEN_14 | _GEN_15 | _GEN_16 | _GEN_17 | _GEN_18
    | _GEN_19;
  wire             _GEN_22 = _GEN_21 | _GEN_20;
  wire             _GEN_23 = io_read_readMEM1_result_in_data[30:24] == 7'h67;
  wire             _GEN_24 = io_read_readMEM1_result_in_data[30:24] == 7'h3;
  wire             _GEN_25 =
    _GEN_0 | _GEN_1 | ~(|(io_read_readMEM1_result_in_data[22:20])) | _GEN_5;
  wire             _GEN_26 = _GEN_25 | _GEN_2;
  wire             _GEN_27 = io_read_readMEM1_result_in_data[30:24] == 7'h63;
  wire             _GEN_28 =
    _GEN_2 | ~(|(io_read_readMEM1_result_in_data[22:20])) | _GEN_0 | _GEN_4
    | (&(io_read_readMEM1_result_in_data[22:20]));
  wire             _GEN_29 = _GEN_28 | _GEN_1;
  wire             _GEN_30 = io_read_readMEM1_result_in_data[30:24] == 7'h23;
  wire             _GEN_31 = _GEN_5 | _GEN_1;
  wire             _GEN_32 =
    _GEN_30 & (_GEN_31 | ~(|(io_read_readMEM1_result_in_data[22:20])));
  wire             _GEN_33 = _GEN_27 ? _GEN_29 : _GEN_32;
  wire [4:0]       rs1 = io_read_readMEM1_result_in_data[19:15];
  wire [4:0]       readX1_addr = io_read_readMEM1_result_in_data[24:20];
  wire             readX0_enable =
    (|rs1)
    & (_GEN
         ? _GEN_8
         : _GEN_9
             ? _GEN_22
             : _GEN_23
                 ? ~(|(io_read_readMEM1_result_in_data[22:20]))
                 : _GEN_24 ? _GEN_26 : _GEN_33);
  wire [31:0]      sig_79 = io_fwd_X0_en_in ? io_fwd_X0_val_in : io_readX0_result_in_data;
  wire             readX1_enable =
    (|readX1_addr) & ~_GEN & (_GEN_9 ? _GEN_22 : ~(_GEN_23 | _GEN_24) & _GEN_33);
  wire [31:0]      sig_85 = io_fwd_X1_en_in ? io_fwd_X1_val_in : io_readX1_result_in_data;
  wire             _GEN_34 = io_read_readMEM1_result_in_data[30:24] == 7'h6F;
  wire             _GEN_35 = io_read_readMEM1_result_in_data[30:24] == 7'h37;
  wire             _GEN_36 = io_read_readMEM1_result_in_data[30:24] == 7'h17;
  wire             _GEN_37 = _GEN | _GEN_9;
  wire             _GEN_38 = _GEN_37 | _GEN_23;
  wire             _GEN_39 = _GEN_38 | _GEN_24;
  wire             _GEN_40 = _GEN_34 | _GEN_35;
  wire             _GEN_41 = _GEN_27 | _GEN_30;
  wire             _GEN_42 = _GEN_24 | _GEN_27;
  wire [31:0]      writeX0_value = {io_read_readMEM1_result_in_data[31:12], 12'h0};
  wire [19:0]      _GEN_43 = {20{io_read_readMEM1_result_in_data[31]}};
  wire [7:0][31:0] _GEN_44 =
    {{32'h0},
     {32'h0},
     {32'h0},
     {{{20{io_read_readMEM1_result_in_data[31]}},
       io_read_readMEM1_result_in_data[7],
       io_read_readMEM1_result_in_data[30:25],
       io_read_readMEM1_result_in_data[11:8],
       1'h0}},
     {{_GEN_43,
       io_read_readMEM1_result_in_data[31:25],
       io_read_readMEM1_result_in_data[11:7]}},
     {{{12{io_read_readMEM1_result_in_data[31]}},
       io_read_readMEM1_result_in_data[19:12],
       io_read_readMEM1_result_in_data[20],
       io_read_readMEM1_result_in_data[30:21],
       1'h0}},
     {writeX0_value},
     {{_GEN_43, io_read_readMEM1_result_in_data[31:20]}}};
  always @(posedge clock) begin
    if (reset) begin
      rd <= 5'h0;
      rs2 <= 5'h0;
      readMEM0_addr <= 32'h0;
      rs1_neq_0 <= 1'h0;
      rs2_neq_0 <= 1'h0;
      n204 <= 32'h0;
      writeX0_enable <= 1'h0;
      is_JALRBEQBLTBGEBGEUBNEJALBLTU <= 1'h0;
      is_S <= 1'h0;
      is_L <= 1'h0;
      n248 <= 3'h0;
      bin_writePC0_value <= 2'h0;
      bin_readMEM0_words <= 2'h0;
      sel_writeMEM0_words <= 2'h0;
      bin_writeX0_value <= 3'h0;
      sel_readMEM0_addr <= 5'h0;
      invalid_insn <= 1'h0;
      readX0_result <= 32'h0;
      readX1_result <= 32'h0;
      readMEM1_addr <= 32'h0;
      writePC1_value <= 32'h0;
    end
    else if (io_DECODE_en_in) begin
      rd <= io_read_readMEM1_result_in_data[11:7];
      rs2 <= io_read_readMEM1_result_in_data[24:20];
      readMEM0_addr <= writeX0_value;
      rs1_neq_0 <= |rs1;
      rs2_neq_0 <= |readX1_addr;
      n204 <=
        _GEN_44[_GEN_39
                  ? 3'h0
                  : _GEN_27
                      ? {_GEN_2 | ~(|(io_read_readMEM1_result_in_data[22:20])) | _GEN_0
                           | _GEN_4 | (&(io_read_readMEM1_result_in_data[22:20]))
                           | _GEN_1,
                         2'h0}
                      : _GEN_30
                          ? (_GEN_31 | ~(|(io_read_readMEM1_result_in_data[22:20]))
                               ? 3'h3
                               : 3'h0)
                          : _GEN_34 ? 3'h2 : _GEN_35 ? 3'h0 : {2'h0, _GEN_36}];
      writeX0_enable <=
        (|(io_read_readMEM1_result_in_data[11:7]))
        & (_GEN
             ? _GEN_8
             : _GEN_9
                 ? _GEN_22
                 : _GEN_23
                     ? ~(|(io_read_readMEM1_result_in_data[22:20]))
                     : _GEN_24 ? _GEN_26 : ~_GEN_41 & (_GEN_40 | _GEN_36));
      is_JALRBEQBLTBGEBGEUBNEJALBLTU <=
        ~_GEN_37
        & (_GEN_23
             ? ~(|(io_read_readMEM1_result_in_data[22:20]))
             : ~_GEN_24 & (_GEN_27 ? _GEN_29 : ~_GEN_30 & _GEN_34));
      is_S <= ~(_GEN | _GEN_9 | _GEN_23 | _GEN_42) & _GEN_32;
      is_L <= ~(_GEN | _GEN_9 | _GEN_23) & _GEN_24 & _GEN_26;
      n248 <=
        _GEN_37
          ? 3'h0
          : _GEN_23
              ? {3{~(|(io_read_readMEM1_result_in_data[22:20]))}}
              : _GEN_24
                  ? 3'h0
                  : _GEN_27
                      ? (_GEN_2
                           ? 3'h2
                           : (|(io_read_readMEM1_result_in_data[22:20]))
                               ? (_GEN_0
                                    ? 3'h4
                                    : _GEN_4
                                        ? 3'h5
                                        : (&(io_read_readMEM1_result_in_data[22:20]))
                                            ? 3'h3
                                            : {2'h0, _GEN_1})
                               : 3'h0)
                      : _GEN_30 | ~_GEN_34 ? 3'h0 : 3'h6;
      bin_writePC0_value <=
        _GEN_37
          ? 2'h0
          : _GEN_23
              ? {~(|(io_read_readMEM1_result_in_data[22:20])), 1'h0}
              : _GEN_42 | _GEN_30 ? 2'h0 : {1'h0, _GEN_34};
      bin_readMEM0_words <=
        _GEN_38 | ~_GEN_24 | _GEN_0
          ? 2'h0
          : _GEN_1
              ? 2'h2
              : (|(io_read_readMEM1_result_in_data[22:20]))
                  ? (_GEN_5 ? 2'h1 : {_GEN_2, 1'h0})
                  : 2'h0;
      sel_writeMEM0_words <=
        _GEN_39 | _GEN_27 | ~_GEN_30 ? 2'h0 : _GEN_5 ? 2'h2 : {1'h0, _GEN_1};
      bin_writeX0_value <=
        _GEN
          ? (_GEN_0
               ? 3'h5
               : _GEN_1
                   ? ((|(io_read_readMEM1_result_in_data[7:1])) ? 3'h0 : 3'h5)
                   : (_GEN_2
                        ? ~(|(io_read_readMEM1_result_in_data[7:1])) | _GEN_3
                        : (&(io_read_readMEM1_result_in_data[22:20]))
                          | ~(|(io_read_readMEM1_result_in_data[22:20])) | _GEN_4 | _GEN_5
                          | _GEN_6)
                       ? 3'h5
                       : 3'h0)
          : _GEN_9
              ? (_GEN_11 | _GEN_12 | _GEN_13 | _GEN_14 | _GEN_15 | _GEN_16 | _GEN_17
                 | _GEN_18 | _GEN_19 | _GEN_20
                   ? 3'h5
                   : 3'h0)
              : _GEN_23
                  ? ((|(io_read_readMEM1_result_in_data[22:20])) ? 3'h0 : 3'h5)
                  : _GEN_24
                      ? (_GEN_0
                           ? 3'h1
                           : _GEN_1
                               ? 3'h2
                               : (|(io_read_readMEM1_result_in_data[22:20]))
                                   ? (_GEN_5 ? 3'h4 : _GEN_2 ? 3'h3 : 3'h0)
                                   : 3'h0)
                      : _GEN_41 | ~(_GEN_34 | _GEN_35 | _GEN_36) ? 3'h0 : 3'h5;
      sel_readMEM0_addr <=
        _GEN
          ? (_GEN_0
               ? 5'hF
               : _GEN_1
                   ? ((|(io_read_readMEM1_result_in_data[7:1])) ? 5'h0 : 5'h14)
                   : _GEN_2
                       ? ((|(io_read_readMEM1_result_in_data[7:1]))
                            ? (_GEN_3 ? 5'h16 : 5'h0)
                            : 5'h15)
                       : (&(io_read_readMEM1_result_in_data[22:20]))
                           ? 5'hD
                           : (|(io_read_readMEM1_result_in_data[22:20]))
                               ? (_GEN_4 ? 5'hE : _GEN_5 ? 5'h10 : _GEN_6 ? 5'h11 : 5'h0)
                               : 5'hC)
          : _GEN_9
              ? (_GEN_11
                   ? 5'h9
                   : _GEN_12
                       ? 5'h8
                       : _GEN_13
                           ? 5'h6
                           : _GEN_14
                               ? 5'h3
                               : _GEN_15
                                   ? 5'hA
                                   : _GEN_16
                                       ? 5'h5
                                       : _GEN_17
                                           ? 5'h2
                                           : _GEN_18
                                               ? 5'h4
                                               : _GEN_19 ? 5'h7 : _GEN_20 ? 5'hB : 5'h0)
              : _GEN_23
                  ? ((|(io_read_readMEM1_result_in_data[22:20])) ? 5'h0 : 5'h17)
                  : _GEN_24
                      ? {4'h0,
                         _GEN_0 | _GEN_1 | ~(|(io_read_readMEM1_result_in_data[22:20]))
                           | _GEN_5 | _GEN_2}
                      : _GEN_41
                          ? 5'h0
                          : _GEN_34 ? 5'h17 : _GEN_35 ? 5'h13 : _GEN_36 ? 5'h12 : 5'h0;
      invalid_insn <=
        _GEN
          ? ~_GEN_0
            & (_GEN_1
                 ? (|(io_read_readMEM1_result_in_data[7:1]))
                 : _GEN_2
                     ? (|(io_read_readMEM1_result_in_data[7:1]))
                       & io_read_readMEM1_result_in_data[7:1] != 7'h20
                     : ~_GEN_7 & io_read_readMEM1_result_in_data[22:20] != 3'h3)
          : _GEN_9
              ? ~_GEN_21 & _GEN_10 != 10'h2A0
              : _GEN_23
                  ? (|(io_read_readMEM1_result_in_data[22:20]))
                  : _GEN_24
                      ? ~_GEN_25 & io_read_readMEM1_result_in_data[22:20] != 3'h5
                      : _GEN_27
                          ? ~_GEN_28 & io_read_readMEM1_result_in_data[22:20] != 3'h1
                          : _GEN_30
                              ? ~_GEN_31 & (|(io_read_readMEM1_result_in_data[22:20]))
                              : ~_GEN_40
                                & io_read_readMEM1_result_in_data[30:24] != 7'h17;
      readX0_result <= sig_79;
      readX1_result <= sig_85;
      readMEM1_addr <= io_read_readMEM1_addr_in_data;
      writePC1_value <= io_read_writePC1_value_in_data;
    end
  end // always @(posedge)
  assign io_readX0_result_in_enable =
    io_read_DECODE_full_in_data & readX0_enable & ~io_fwd_X0_en_in;
  assign io_readX0_result_in_address = rs1;
  assign io_readX1_result_in_enable =
    io_read_DECODE_full_in_data & readX1_enable & ~io_fwd_X1_en_in;
  assign io_readX1_result_in_address = readX1_addr;
  assign io_read_n248_out_data = n248;
  assign io_read_rs1_neq_0_out_data = rs1_neq_0;
  assign io_read_readX0_result_out_data = readX0_result;
  assign io_read_rs2_neq_0_out_data = rs2_neq_0;
  assign io_read_readX1_result_out_data = readX1_result;
  assign io_read_writePC1_value_0_out_data = writePC1_value;
  assign io_read_readMEM1_addr_0_out_data = readMEM1_addr;
  assign io_read_n204_out_data = n204;
  assign io_read_is_JALRBEQBLTBGEBGEUBNEJALBLTU_out_data = is_JALRBEQBLTBGEBGEUBNEJALBLTU;
  assign io_read_bin_writePC0_value_out_data = bin_writePC0_value;
  assign io_read_sel_readMEM0_addr_out_data = sel_readMEM0_addr;
  assign io_read_readMEM0_addr_out_data = readMEM0_addr;
  assign io_read_rs2_out_data = rs2;
  assign io_read_is_S_out_data = is_S;
  assign io_read_sel_writeMEM0_words_out_data = sel_writeMEM0_words;
  assign io_read_invalid_insn_out_data = invalid_insn;
  assign io_read_bin_writeX0_value_out_data = bin_writeX0_value;
  assign io_read_bin_readMEM0_words_out_data = bin_readMEM0_words;
  assign io_read_is_L_out_data = is_L;
  assign io_read_writeX0_enable_out_data = writeX0_enable;
  assign io_read_rd_out_data = rd;
  assign io_rs1_out = rs1;
  assign io_readX1_addr_out = readX1_addr;
  assign io_readX0_enable_out = readX0_enable;
  assign io_readX1_enable_out = readX1_enable;
endmodule

